### ISSUE TITLE
Retry? 

### ISSUE THREAD

**Issue by jkoenig72** [sidoh/esp8266_milight_hub#114]
Love it! Cool work. Only issue I have is that sometimes not all lights turn on/off. Any way to configure some retry?

Regards
Joerg

**Comment by sidoh** [comment]
There's a setting called `packet_repeats` in the UI. 50 is a good balance for my setup.

**Comment by jkoenig72** [comment]
Thanks! Will try that... again great work. Integration with home assistant works like charm....

**Comment by sidoh** [comment]
Glad it works for you!

Gonna close this since it sounds like that setting was what you were looking for, but feel free to reopen if you run into problems.
