### ISSUE TITLE
failed upload index.html

### ISSUE THREAD

**Issue by turuwhiska** [sidoh/esp8266_milight_hub#12]
i have thi error when i try upload de ui Error updating web file
i use the command curl -vvv -X POST -F 'image=@web/index.html' http://<ip_of_esp>/web

**Comment by sidoh** [comment]
Are you replacing `<ip_of_esp>` with an IP?

**Comment by sidoh** [comment]
Looks like this is you:

http://blog.christophermullins.com/2017/02/11/milight-wifi-gateway-emulator-on-an-esp8266/#comment-1136

so sounds like you are.

The logs you included from the Serial console make it sound like your ESP has different flash sizes than the firmware you pushed to it. Are you using one of the pre-compiled firmware binaries? What ESP breakout model are you using?

**Comment by turuwhiska** [comment]
yes i remplace  <ip_of_esp> , im using esp8266-12 , i tested the two pre-compilated files
its posible compile for esp-12?

**Comment by turuwhiska** [comment]
ist posible use in esp-01? how can make? dont have a makefile thank so much for response from argentina

**Comment by sidoh** [comment]
Should be possible to compile it for esp-12. Just add a new environment in `platformio.ini`. Here's a copy from another project where I used an esp-12f:

```
[env:esp12f]
platform = espressif8266
board = esp12e
framework = arduino
build_flags = -Wl,-Tesp8266.flash.4m1m.ld
```

I needed to specify the custom `build_flags`. I think the platformio defaults were wrong, or at least didn't work with the device I had. YMMV.

Don't think this will work with esp-01. The nrf24l01 is an SPI device, and the esp-01 doesn't expose the SPI GPIOs (12-15, esp-01 only exposes GPIO 0/2).

**Comment by turuwhiska** [comment]
ah perfect i will test how you compile? make its not posible?

**Comment by sidoh** [comment]
Probably easiest to use [platformio](http://platformio.org/). Basically just open up the project, add the section to `platformio.ini`, and run compile :)

**Comment by sidoh** [comment]
@turuwhiska were you able to get this working? I can upload an esp-12 binary if it'd help.

**Comment by turuwhiska** [comment]
i dont test becouse dont have internet for download platformio. (the life in patogonia)  if you cau upload the bin for esp-12 perfect!!!, thank so much

**Comment by turuwhiska** [comment]
Super , if you can upload the Bin file foro esp-12 perfect . I dont have internet foro Download platformio . The Life in Patagonia jaja

El 11 mar. 2017 0:14, Chris Mullins <notifications@github.com> escribió:

@turuwhiska<https://github.com/turuwhiska> were you able to get this working? I can upload an esp-12 binary if it'd help.

**Comment by turuwhiska** [comment]
can you upload the bin file?

**Comment by terrag42** [comment]
@sidoh I tried to build from source and got the error:
`src\main.cpp:2:25: fatal error: WiFiManager.h: No such file or directory`
Should the WiFiManager library be included in the "libs" folder?

**Comment by turuwhiska** [comment]
i installed atom and platformio but i can install the board sdk. internet in patagonia argentina its a probtlem,
if you can upload the file i thank you so much

**Comment by sidoh** [comment]
Sorry for the delay. Here it is:

https://github.com/sidoh/esp8266_milight_hub/blob/master/dist/firmware-esp12.bin

**Comment by turuwhiska** [comment]
thanks so much . i tested the new .bin and had the same problem
*WM: AutoConnect                                                                
*WM: Connecting as wifi client...                                               
*WM: Using last saved values, should be faster                                  
*WM: Connection result:                                                         
*WM: 3                                                                          
*WM: IP Address:                                                                
*WM: 192.168.43.152                                                             
Opening settings file failed 


and when i try upload de webui 

Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file

**Comment by turuwhiska** [comment]
and i used sudo ./esptool.py --port /dev/ttyUSB0 erase_flash

**Comment by sidoh** [comment]
Hmm... are you able to link to the device you bought?

**Comment by turuwhiska** [comment]
What would that be?

**Comment by sidoh** [comment]
I mean the ESP. Can you link to where you got it from?

All I can figure is that the flash sizes are different from the one I have.

**Comment by turuwhiska** [comment]
sure. Is it possible to add the ui in the bin?

**Comment by sidoh** [comment]
Yeah - definitely something I want to do. That's the idea behind #2, although the approach I was planning on taking here wouldn't solve the issue you're having (seems like the bin is still not compatible with your device).

I'll test with an esp12 myself soon. Trying to get the new RGB+CCT protocol finished.

**Comment by turuwhiska** [comment]
ok thank so much!!!

**Comment by sidoh** [comment]
Can you show me the esp12 you have? Link to where you bought it from or maybe take a picture?

**Comment by turuwhiska** [comment]
im sorry is the model esp8266-07
http://www.prometec.net/producto/esp8266-esp-07/

**Comment by turuwhiska** [comment]
its posible use in esp-07?

**Comment by fireboy1919** [comment]
BTW, this also didn't work for me until I did this:
curl -vvv -X POST -F 'image=@web/index.html' http://<ip_of_esp>/web -u "":""

I was getting unauthorized errors.

**Comment by sidoh** [comment]
Here's firmware for the esp07:

https://github.com/sidoh/esp8266_milight_hub/blob/master/dist/firmware-esp07.bin

@fireboy1919, are you running with the latest version? I thought I fixed that.

**Comment by turuwhiska** [comment]
Thanks i Will test now

El 20 mar. 2017 13:56, Chris Mullins <notifications@github.com> escribió:

Here's firmware for the esp07:

https://github.com/sidoh/esp8266_milight_hub/blob/master/dist/firmware-esp07.bin

@fireboy1919<https://github.com/fireboy1919>, are you running with the latest version? I thought I fixed that.

**Comment by turuwhiska** [comment]
i tested the new bin for esp07
the same error :
*WM: Connecting as wifi client...                                               
*WM: Using last saved values, should be faster                                  
*WM: Connection result:                                                         
*WM: 3                                                                          
*WM: IP Address:                                                                
*WM: 192.168.43.152                                                             
Opening settings file failed                                                    
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file                                                         
Error updating web file

**Comment by sidoh** [comment]
I tested with a fresh esp07 and it worked just fine. How are you flashing the firmware? Can you paste the command you're using? I used this:

```
python /opt/esptool/esptool.py --port /dev/cu.SLAB_USBtoUART --baud 115200 write_flash -fm=dio -fs=1MB 0x00000 .pioenvs/esp07/firmware.bin
```

Note that you need to use `-fs=1MB` for esp07 instead of `-fs=4MB` because it only has 1MB of flash.

**Comment by turuwhiska** [comment]
yes!!!!!!!! perfect thanks so much!!!!!work!!
close the inssue?

**Comment by sidoh** [comment]
Awesome, glad that part's working. Sure, sounds like we can close.
