### ISSUE TITLE
Add a password to the WiFi in Access Point Mode

### ISSUE THREAD

**Issue by speendo** [sidoh/esp8266_milight_hub#123]
This project uses [WiFiManager](https://github.com/tzapu/WiFiManager) to configure the WiFi settings of the ESP8266.

This means, whenever the ESP8266 can not access another WiFi it turns to Access Point Mode and provides a web page to connect to another already existing WiFi.

The code for that is [here](https://github.com/sidoh/esp8266_milight_hub/blob/master/src/main.cpp#L153):

    wifiManager.autoConnect();

The [documentation](https://github.com/tzapu/WiFiManager#documentation) of WiFiManager states that

> You can and should password protect the configuration access point.

And for a good reason: entering my *secret* WiFi passphrase to an unencrypted web page on an unencrypted WiFi is a severe security flaw. If my neighbor is sniffing my WiFi traffic, she can then extract my WiFi passphrase, enter my WiFi (and then maybe play around with my NAS). So altoghether this is not the same but right next to not having a protected WiFi altogether.

The easy solution for this problem would be something like

    wifiManager.autoConnect("ESP" + String(ESP.getChipId()), "<some password, at least 8 chars>");

Instead of just `wifiManager.autoConnect();`

(the AP name part is "stolen" from [here](https://github.com/tzapu/WiFiManager/blob/master/WiFiManager.cpp#L135)).

**Comment by sidoh** [comment]
Thanks for raising this.  It's something I've been meaning to do.  I actually just configure my ESPs with wifi credentials over serial for this reason.

I'll work this into v1.6.
