### ISSUE TITLE
Off Command via UDP Doesn't Seem to work with 1.6.0dev6

### ISSUE THREAD

**Issue by GreenTentacle** [sidoh/esp8266_milight_hub#126]
I can send all commands from the milight-hub.local's web interface, and can send color and level changes over UDP (via Domoticz), but sending on/off commands via UDP doesn't seem to do anything.

Thanks for all the hard work, this is a great project !

**Comment by sidoh** [comment]
What UDP version (5/6) and what bulb type are you using?

**Comment by sidoh** [comment]
Can you try [1.6.0-dev7](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.6.0-dev7)?  Thinking this might be related to #115.

**Comment by GreenTentacle** [comment]
It was v5, with an RGBW bulb.  And dev7 did, in fact, fix it !  Thanks !

**Comment by sidoh** [comment]
Great, glad that did the trick.  Thanks for raising!
