### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by vr6syncro** [sidoh/esp8266_milight_hub#129]
Not a issue its a question.

At the moment i use the original Gateway and some not original Lights. Milight has the Night Mode. 
My Problem: it semms  that the Nightmode Brightness are set to low for my light. They are not lightning.

Is it possible to change Night Mode value with this alternativ Gateway? Or is this option stored on the Device?

Thank You

**Comment by vr6syncro** [comment]
thanks for reply. 
with my gateway i only can push a button for brightness and i cant see the aktual value. is it available at this software to set a value and see the status?

**Comment by sidoh** [comment]
Kind of.  You can give it a particular brightness value and it sets it by dimming the bulbs all the way (pressing down 10x), then pressing up the appropriate number of times.  Not completely reliable, but  works well enough.

**Comment by vr6syncro** [comment]
ok that help me thanks
