### ISSUE TITLE
add to wiki

### ISSUE THREAD

**Issue by rhamblen** [sidoh/esp8266_milight_hub#134]
Useful if you add one thing to wiki... (I couldnt see how to do it myself)

Integration to SMARTTHINGS
https://github.com/fireboy1919/MiThings

Ive been using this since I discovered you and it works perfectly.
Also it is now integrated with Alexa and works perfectly as well.

Just useful for people to link back to.

**Comment by sidoh** [comment]
Sounds like a good idea.

I've not tried this myself, but I think you can contribute to the wiki by forking/cloning https://github.com/sidoh/esp8266_milight_hub.wiki.git.

**Comment by Lstt2005** [comment]
Very interesting catalogs - compatibles and other information if 2 files:
[MiLight-ProductCatalog-2017_other.pdf](https://github.com/sidoh/esp8266_milight_hub/files/1379130/MiLight-ProductCatalog-2017_other.pdf)
[MiLight-ProductCatalog-2017.pdf](https://github.com/sidoh/esp8266_milight_hub/files/1379131/MiLight-ProductCatalog-2017.pdf)

**Comment by sidoh** [comment]
Added a link to @fireboy1919's repo to the wiki.  Also added the product catalog.
