### ISSUE TITLE
Reset Wifi-Config-Buttons does not work

### ISSUE THREAD

**Issue by bombcheck** [sidoh/esp8266_milight_hub#135]
Running the latest 1.6.0-dev8 but can not reset die Wifi-Config via the button in the web gui.

Beside this little flaw this project is amazing! Looking forward to replace my four milight wifi bridges at home. :)

**Comment by bombcheck** [comment]
Reflash does not fix this... Had to use esptool to wipe flash, then reflash the firmware...

**Comment by sidoh** [comment]
WiFi credentials are stored in a reserved area of flash that isn't overwritten when writing new firmware.  

#125 aimed at fixing the API/UI feature, but I've not had the chance to verify that it did.

**Comment by bombcheck** [comment]
Yeah, saw that one... Seems the fix does not work as intended. :)

**Comment by bombcheck** [comment]
OK just checked this one out: Does NOT work with latest pre-compiled 1.6.0-DEV8.
But it DOES work when compiling from latest source branch (v1.6.0).
