### ISSUE TITLE
Fix serious newly discovered WPA2 security flaws

### ISSUE THREAD

**Issue by RvonMallesch** [sidoh/esp8266_milight_hub#137]
Severe flaws in WPA2 have been found. The details can be found here https://www.krackattacks.com/

**Comment by sidoh** [comment]
This will involve building against the updated Arduino SDK, which includes Espressif's patched Non-OS SDK.  Might be some compatibility issues to sort through, but shouldn't be too complicated.

https://github.com/esp8266/Arduino/issues/3725

**Comment by RvonMallesch** [comment]
Thanks :-)

**Comment by sidoh** [comment]
Fixed in [1.6.0-dev9](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.6.0-dev9).
