### ISSUE TITLE
No way to delete unused ID's from drop down list

### ISSUE THREAD

**Issue by RvonMallesch** [sidoh/esp8266_milight_hub#146]
Hi,

Is there a way to delete an ID from the drop down list? Ideally, if an ID was no longer linked to any bulbs it would disappear.

Regards,

Richard

**Comment by sidoh** [comment]
There isn't currently a way through the UI, but you can set the list to whatever you want via the REST API:

```
curl -v -X PUT -d '{"device_ids":[1,2,3]}' http://milight-hub.local/settings
```

There's no way for this to happen automatically, though.  There's no way to determine the number of bulbs linked to a particular ID.

**Comment by RvonMallesch** [comment]
OK thanks :-)

**Comment by sidoh** [comment]
Want to make sure I'm understanding your suggestion.  Were you asking if there's a way to do it in the UI?  That's totally reasonable and should probably be a thing.  I also think it'd be nice if the IDs in the dropdown auto-saved (they are currently only persisted when you save settings).

**Comment by servim** [comment]
and if the identifier is only one, you need it to be selected automatically :)

**Comment by sidoh** [comment]
Fair point.  Perhaps the most general way to handle that is to have the browser remember the last selected ID via local storage.
