### ISSUE TITLE
State of group 4 not stored when sending to group 0

### ISSUE THREAD

**Issue by hencou** [sidoh/esp8266_milight_hub#154]
In 1.6RC3, the state of group 4 is not stored when sending a command to group 0.

In file /lib/MiLightState/GroupStateStore.cpp line 32:
`for (size_t i = 1; i < remote->numGroups; i++) {`

Should be:
`for (size_t i = 1; i <= remote->numGroups; i++) {`

**Comment by sidoh** [comment]
Fixed in https://github.com/sidoh/esp8266_milight_hub/commit/f6a66ff599aa12ce7a9e62f0eb6ef65acba2f5f5.  Will create a release later today.

Thanks for reporting the bug, and for digging into the solution!  :)
