### ISSUE TITLE
Pre-compiled version is password protected

### ISSUE THREAD

**Issue by Labzz** [sidoh/esp8266_milight_hub#156]
Hi, i tried to flash my NodeMCU with the latest pre-compiled version (pre-release 1.6.0-rc3) with the NodeMCU Flasher software for Windows. After replugging the power the ESPxxxxx network was shown as expected but password protected. 

I picked up my Wemos D1 mini, downloaded another binary file from pre-release 1.6.0-rc3 and uploaded it, but also password protected. 

About 1 month ago I followed the exact same steps with success. So I downloaded an older pre-compiled binary from release 1.5.0 and it worked. 

If the password protected feature is added? Cool! but what is the password? I couldn't find it in the code too. Otherwise something strange happened it the past :).

**Comment by sidoh** [comment]
The README for the v1.6.0 branch includes the password:

https://github.com/sidoh/esp8266_milight_hub/tree/v1.6.0

It's `milightHub`.

Please feel free to reopen if this doesn't answer your question.
