### ISSUE TITLE
problem with v1.6.0rc4 wifi setup

### ISSUE THREAD

**Issue by khmann** [sidoh/esp8266_milight_hub#158]
I bought this nodeMCUv2: https://www.amazon.com/gp/product/B010O1G1ES/
I tried to flash the file esp8266_milight_hub_nodemcuv2-1.6.0-rc4.bin, several times under OS/X with the git esptool.

Every time, I got an encrypted network shown ESP5431332 which I couldn't connect wether I used password "configesp" or anything else it was the same

I flashed the release v1.5 and the network was open, setup completed, connected to my network.

I then re-flashed the 1.6rc4 again via esptool and everything was still working.  Seems something is strange in the "setup wifi", just fyi.

**Comment by khmann** [comment]
update.  Clicking "clear wifi config" button has the same affect.  must reflash v1.5 to get the "connectable ssid" back

**Comment by khmann** [comment]
Sorry, I'm a n00b, I found "closed issue #156".  nvm.

**Comment by sidoh** [comment]
Haha glad you figured it out.  Definitely pretty confusing while v1.6.0 is still in prerelease.  Planning on releasing soon so hopefully won't be a problem for much longer :)
