### ISSUE TITLE
FUT018

### ISSUE THREAD

**Issue by TH3MA5K** [sidoh/esp8266_milight_hub#166]
Hello,

In the docs the FUT018 bulbs are not present. So they are not compatible?

**Comment by sidoh** [comment]
I've not tested with it, but it should work just fine.  The [product catalogue](https://github.com/sidoh/esp8266_milight_hub/files/1379131/MiLight-ProductCatalog-2017.pdf) says FUT018/GU10 bulbs support FUT092 ("RGB+CCT") and FUT096 ("RGBW") remotes, both of which are implemented by espMH.

**Comment by garmck** [comment]
@TH3MA5K i have these bulbs and they work fine as RGBW

**Comment by sidoh** [comment]
Thanks for confirming, @garmck!

@TH3MA5K, going to close this, but feel free to reopen if you encounter issues.
