### ISSUE TITLE
send and receive errors

### ISSUE THREAD

**Issue by balert** [sidoh/esp8266_milight_hub#174]
Please mention on your wiki page or where else you consider appropriate that using a 10uF capacitor between Vcc and Gnd of the NRF24 module can save you hours of debugging, as in my case light switching didn't work without it, but works perfectly like a charm with the capacitor in place. I originally read about this at http://arduino-info.wikispaces.com/Nrf24L01-2.4GHz-HowTo so it's actually not my own idea but I thought mentioning it could help others.

**Comment by sidoh** [comment]
Interesting.  I've not needed this.  Perhaps it depends on the dev board and the power supply you're using?  I've also dismissed a bunch of NRF modules as junk, and maybe this is all they needed.  Will give it a try.

**Comment by bombcheck** [comment]
Have those capacitor on my modules, too. Does not work to well without...
Here is some input: https://arduino-info.wikispaces.com/Nrf24L01-2.4GHz-HowTo

**Comment by sidoh** [comment]
Updated the troubleshooting guide:

https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting

thanks for pointing this out!
