### ISSUE TITLE
failed upload index.html

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#19]
Hello! I try to upload to index.html to ESP ![23-03-2017 153740](https://cloud.githubusercontent.com/assets/6728198/24248089/093b88ba-0fdf-11e7-82c4-35ac58d80299.jpg)
After, i try view content on it and i see - 
![23-03-2017 154120](https://cloud.githubusercontent.com/assets/6728198/24248153/4e9acdb2-0fdf-11e7-8ea3-8b92abfbdba9.jpg)

**Comment by Lstt2005** [comment]
![23-03-2017 203417](https://cloud.githubusercontent.com/assets/6728198/24261518/47eee18c-1008-11e7-9169-c3bb7aacfefc.jpg)

**Comment by sidoh** [comment]
`/download_update` is only supported in a branch I haven't merged yet.

Did you try restarting the ESP after uploading the UI?

**Comment by Lstt2005** [comment]
Yes, of course. I flash whole my NODE MCU with blank.bin 4Mbytes, try upload via PlatformIO, tru flash you distrib in github - same result...(

**Comment by sidoh** [comment]
I've seen it not work right after uploading, and for whatever stupid reason it's there after restarting the ESP.

If it's consistently not working, I think it can only mean the flash size settings in the distributed firmware are a mismatch for the device you're pushing it to.

**Comment by Lstt2005** [comment]
I have the same Lolin
![23-03-2017 204514](https://cloud.githubusercontent.com/assets/6728198/24261993/c6534b3e-1009-11e7-96fe-5eccf801fbe4.jpg)

**Comment by sidoh** [comment]
Can you share the command you're using to flash it?

**Comment by Lstt2005** [comment]
In PlatformIO
[03/23/17 20:53:25] Processing nodemcuv2 (platform: espressif8266, board: nodemcuv2, framework: arduino)
 Verbose mode can be enabled via `-v, --verbose` option
Collected 32 compatible libraries
Looking for dependencies...
Library Dependency Graph
|   |-- <MiLight>
|   |   |-- <RF24> v1.1.7
|   |   |   |-- <SPI> v1.0
|   |-- <Settings>
|   |   |-- <ArduinoJson> v5.8.3
|   |   |-- <Helpers>
|   |-- <ESP8266WebServer> v1.0

|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ArduinoJson> v5.8.3
|   |-- <Vector>
|   |-- <Helpers>
|   |-- <ESP8266WiFi> v1.0
|-- <WifiManager> v0.12
|   |-- <DNSServer> v1.1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WebServer> v1.0
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266WiFi> v1.0
|-- <Helpers>
|-- <ArduinoJson> v5.8.3
|-- <SPI> v1.0
|-- <Settings>
|   |-- <ArduinoJson> v5.8.3
|   |-- <Helpers>
Linking .pioenvs\nodemcuv2\firmware.elf
Checking program size
text       data     bss     dec     hex filename
358054     8948   30488  397490   610b2 .pioenvs\nodemcuv2\firmware.elf
Building .pioenvs\nodemcuv2\firmware.bin
Looking for upload port...
Auto-detected: COM3
Uploading .pioenvs\nodemcuv2\firmware.bin
Uploading 371152 bytes from .pioenvs\nodemcuv2\firmware.bin to flash at 0x00000000
................................................................................ [ 22% ]
................................................................................ [ 44% ]
................................................................................ [ 66% ]
................................................................................ [ 88% ]
...........................................                                      [ 100% ]
 [SUCCESS] Took 42.24 seconds

**Comment by Lstt2005** [comment]
![23-03-2017 205938](https://cloud.githubusercontent.com/assets/6728198/24262641/c31c29ac-100b-11e7-8afd-2f190113ab3f.jpg)

**Comment by Lstt2005** [comment]
I solve the problem. 
1. Run Arduino 1.8.1.
2. Loand ANY sketch
3. Make directory DATA in the folder of sketch.
4. Copy index.html on DATA folder.
5. IN configuration Select "Flash Size 4M (1M SPIIFS)" - ONLY! (not 3M SPIFFS)!
6. In Arduino in Menu select Tools->ESP8266 Sketch Data Upload
7. Restart NodeMCU.
8. Run   curl -u':' -X PUT --data-binary '{"admin_username":""}' 192.168.0.111/settings
9. Open in browser http://192.168.0.111 and make some username and password - submit

If i use balnk user and password, in next time i must input username and password in browser.
![23-03-2017 232404](https://cloud.githubusercontent.com/assets/6728198/24268766/f588cd50-101f-11e7-87ec-5b5d3f197919.jpg)

**Comment by sidoh** [comment]
> In configuration Select "Flash Size 4M (1M SPIIFS)" - ONLY! (not 3M SPIFFS)!

Yeah, I've found that the ESP is super finicky about the flash size parameters. My guess is that you'd see something like this in serial logs:

```
Error updating web file
```

I think Sketch Data Upload is just building and flashing a SPIFFS image, which shouldn't be necessary as long as the flash params are set right. I've found that I'm reliably able to use SPIFFS on a fresh chip (and I've tested with ~10 across 5 different models) if I:

1. Erase flash, regardless of whether or not it's a fresh chip
1. Make sure I'm flashing it with firmware compiled with the correct settings
1. Flash with `esptool.py`

Seems like most people who use this run into trouble getting SPIFFS to work correctly. This is basically the source of all of the problems with settings not saving, trouble uploading the web UI, etc. Probably worth looking into at least documenting the procedures a little better.

**Comment by Lstt2005** [comment]
Maybe in PlatformIO configuration parametrs for esp8266 something wrong?

**Comment by sidoh** [comment]
Yeah, sounds plausible. I've had trouble with default parameters for esp-07 and esp-12 in the past.

**Comment by Lstt2005** [comment]
1. Just add in platrom.ini

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
build_flags = -Wl,-Tesp8266.flash.4m1m.ld
upload_speed = 921600

2. Create a folder data in main project folder.
3. Place in folder data file index.html
4. In treminal run: pio run -e nodemcuv2 -t uploadfs
5. Profit!

I recommend to you modify this intruction in read.me - it's much easier, then use curl etc....
Much more in http://docs.platformio.org/en/stable/platforms/espressif8266.html#uploading-files-to-file-system-spiffs

**Comment by sidoh** [comment]
I use the default build_flags for the modemcuv2 with what appears to be the same hardware and have no issues. I'm not convinced it makes sense to just drop in the settings you pasted and call it fixed.

Right, I'm familiar with platformio's SPIFFS tools. The reason I'm avoiding relying on them here is because I don't want to force people to set up a development environment to use this. As long as you're using the right flags when flashing the firmware (the reason I'd suggest using `esptool.py` is because you have more explicit control over this), I don't actually think using the SPIFFS tools are easier than using curl (maybe not the case if using Windows).

**Comment by Lstt2005** [comment]
Yes, there are, for example, hundreds beginners on esp8266.ru - they using only Windows...For Windows users much easer use Arduino IDE or PlatforIO and nothing else...:)

**Comment by sidoh** [comment]
Alright, fair enough. Probably a good idea to at least mention it as an option. I'll get around to this at some point, but feel free to open a PR if you want. :)

**Comment by Lstt2005** [comment]
No, for me it's just a hobby, nothing else....

**Comment by sidoh** [comment]
Me too :)

I'm going to leave this open as a reminder to flesh out the docs around getting the ESP set up. Thanks for raising!

**Comment by Lstt2005** [comment]
Ok, thank you!

**Comment by sidoh** [comment]
Updated the documentation to suggest using `uploadfs` instead of the HTTP endpoint:

https://github.com/sidoh/esp8266_milight_hub/commit/9e76eeb16799fd6f640aca29d2ec56c19fb2c9ef

Thanks for pushing on that. I initially felt like it was more work, but with all the problems people have had uploading the UI, I think this is better.
