### ISSUE TITLE
I do not see any traffic on my milight hub

### ISSUE THREAD

**Issue by rolfberkenbosch** [sidoh/esp8266_milight_hub#190]
Hi All,

I have a problem and can't figured out what I'm doing wrong. I still not see any traffic when i press the start sniffing button. I have tried the following:
1. Recheck and recheck the cable wirring
2. Reimage the Wemos D1 mini v2
3. Reboot the wemos D1 many times.
4. Put the milight off and on many times.

I have added some photo's, maybe you guys can find my BIG mistake that cost me many hours.

![img_20171220_002320](https://user-images.githubusercontent.com/30292281/34184009-efa584ae-e51d-11e7-85b0-489c8c163704.jpg)
![img_20171220_002329](https://user-images.githubusercontent.com/30292281/34184010-efc9d462-e51d-11e7-8049-b5a64c3551c7.jpg)
![img_20171220_002340](https://user-images.githubusercontent.com/30292281/34184011-efeac956-e51d-11e7-91af-8c4679bc9c86.jpg)
![img_20171220_002147](https://user-images.githubusercontent.com/30292281/34184012-f005e6aa-e51d-11e7-95c5-9e7d7147333d.jpg)
![img_20171220_002237](https://user-images.githubusercontent.com/30292281/34184013-f023d96c-e51d-11e7-8a6e-2f3e6adc197d.jpg)
![img_20171220_002242](https://user-images.githubusercontent.com/30292281/34184014-f043a97c-e51d-11e7-901a-f89ca01b1f6e.jpg)
![img_20171220_002301](https://user-images.githubusercontent.com/30292281/34184015-f068d670-e51d-11e7-9b66-87f26c5e6c54.jpg)
![img_20171220_002314](https://user-images.githubusercontent.com/30292281/34184016-f0994a3a-e51d-11e7-8348-31ab5f075d9f.jpg)

**Comment by sidoh** [comment]
If you haven't already, take a look at the [troubleshooting guide](https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting).

Something that's not in the guide -- some folks (see #174) have mentioned that a 10µF capacitor across Vin and Gnd on the NRF24 can make a big difference.  I've not been able to verify this myself.

**Comment by bombcheck** [comment]
As far as I can see, you are using a transceiver with integrated power amplifier. These models need an extra power source as the NodeMCU does not provide enough power for them.
https://arduino-info.wikispaces.com/Nrf24L01-2.4GHz-HowTo

**Comment by rolfberkenbosch** [comment]
I have tried an otter module without external antenne. Do i need a remote control to find the device id? I just put some  power on the bulb.

**Comment by sidoh** [comment]
Ignoring some very weird corner cases (see #91), bulbs don't send traffic.

If you're just looking to get a new bulb working with espMH, pick whatever device ID you like (between 0x0000 and 0xFFFF) and pair the bulb with it.  (To do this, press the "pair" button in the UI within 5s of supplying power to the bulb).

**Comment by rolfberkenbosch** [comment]
Thanks @sidoh that was the trick! The module works perfect!

**Comment by mames13** [comment]
Hi, I might be having this problem with a second Nodemcuv2 that I just built with the external antenna transceiver similar to what is pictured.  What voltage should the 10µF capacitor be? Thanks!
