### ISSUE TITLE
Crazyradio PA: nRF24LU1+ based USB dongle transciever with amplifier

### ISSUE THREAD

**Issue by SmilyOrg** [sidoh/esp8266_milight_hub#202]
Just found this [Crazyradio PA dongle](https://www.bitcraze.io/crazyradio-pa/) and thought it might be a neat self-contained way to control lights for an entire neighborhood! 😄 

It does feature open firmware that you can update... so I bet with enough work you could plug it in a RPi and have it work with no hardware hacking. 😃

**Comment by sidoh** [comment]
This looks cool, but is probably out of scope for this project.

It probably wouldn't be a crazy amount of work to port the packet handling stuff to another project, but I'm not sure it makes sense to support this device within the same project.

**Comment by SmilyOrg** [comment]
Yeah, I agree. Linked it for relevance :)
