### ISSUE TITLE
Black bulb or color picker in Hass

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [sidoh/esp8266_milight_hub#207]
Hi Chris,

Thanks for the work you did on this.

One issue I have is that I am currently unable to have both the color picker and the light icons reflecting the actual color of the bulb in Home Assistant (v60.1). 
Right now, I can get the icons to change color by using the computed_color: true command or the color picker by using the color: true or rgb:true. 
If using both computed_color: true and one of the other 2 options at the same time, the color picker is on, but the icon is black (R:0, G:0, B:0)...

**Comment by sidoh** [comment]
It sounds like you're changing your HASS config, which shouldn't be necessary.  Select the "computed_color" field in the ESPMH config.

**Comment by MimbaMonkeyHouse** [comment]
Thanks for getting back.
Yes, I did. With the rgb: true setting in Home Assistant, there is no change in bulb color in HA .60.1! What setting should be used in HA?
The ESPMH config is set up with just computed_color...

**Comment by sidoh** [comment]
It was working for me with HASS 0.59.  I just upgraded to 0.61.1, and it's still working.

This is my ESPMH state field config:

<img src="https://user-images.githubusercontent.com/589893/35198598-f5e8354a-fea5-11e7-809e-1a249cc10513.png" height=400 />

The relevant section of my HASS config is in the wiki for this project:

https://github.com/sidoh/esp8266_milight_hub/wiki/HomeAssistant

**Comment by MimbaMonkeyHouse** [comment]
Hi Chris,

Thanks for getting back. I proof checked all settings in both ESPMH (& updated to 1.6.5 nomcu v2) and HASS (v60.1). All is the same as your and here are relevant parts of my lights.yaml for my RGBW, RGB_CCT and CCT respectively:
  state_topic: milight/updates/0x22CB/rgbw/1
  <<: &MILIGHTRGBW_PARAMS
      platform: mqtt_json
      color_temp: false
      rgb: true
      brightness: true
  state_topic: milight/updates/0x224C/rgb_cct/1
  <<: &MILIGHT_PARAMS
      platform: mqtt_json
      rgb: true
      color_temp: true
      brightness: true
  state_topic: milight/updates/0x314/cct/1
  <<: &MILIGHTCCT_PARAMS
      platform: mqtt_json
      color_temp: true
      rgb: false
      brightness: true
      qos: 1
      retain: true
The icon color in HA updates for both RGBW and CCT, but not for RGB-CCT. As explained earlier, if rgb: false and computed_color: true are applied, then the icon color updates, but no color picked is available.

Do you have a solution for RGB-CCT? Should I update GitHub with this so others can ring in?

Cheers

**Comment by sidoh** [comment]
The `rgb` key in the HASS config should not be changed.  It should be set to true.  `computed_color` is an ESPMH config, not HASS.  My HASS section for RGB+CCT is:

```yaml
    state_topic: milight/updates/0x1/rgb_cct/1

    # Use a YAML anchor for common settings so we can just reference
    # them for other lights.
    <<: &MILIGHT_PARAMS
      platform: mqtt_json
      color_temp: true
      rgb: true
      brightness: true
```

**Comment by JSmid6** [comment]
I'm having the same issue with my rgbw bulbs, the cct bulbs work fine.

**Comment by sidoh** [comment]
Both rgbw and rgb+cct work for me. 

![image](https://user-images.githubusercontent.com/589893/35542050-d2734212-0512-11e8-9ca7-7f70f4acc2ed.png)

![image](https://user-images.githubusercontent.com/589893/35542067-e1889932-0512-11e8-94ed-ea8cbed388ce.png)

Please copy/paste your HASS configs and a settings dump from ESPMH (just navigate to http://milight-hub.local/settings), making sure to censor any passwords.

**Comment by garmck** [comment]
Just confirming I **do not** have this issue either - running 0.61.1

**Comment by MimbaMonkeyHouse** [comment]
Thanks for taking the time to reply. 

Mmh, then something is going strangely with my setup. I’ve been getting this with both v60.1, v61.1 and now v62.0… I’m running HA on a Synology docker. I am currently using some of the bulbs with the Milight integration as my RF gateways do not reach far enough to get all lights covered. I use 2 RF gateways. Settings dumps are attached along with my lights.yaml configuration. 

This is leaving me perplexed and I may be missing something obvious… so thanks again!

Cedric

**Comment by MimbaMonkeyHouse** [comment]
I thought you may want to see a screenshot of what I get in HA so here they are. You’ll see the RGB icons are also blacked out when on…

**Comment by JSmid6** [comment]
I changed the settings around and I no longer have this issue. I used the setting as chris mentioned above.

**Comment by sidoh** [comment]
@MimbaMonkeyHouse, if you're attaching things to your messages (via email, it looks like?), they're not coming through.

**Comment by MimbaMonkeyHouse** [comment]
Ok, sorry about that. Guess the monkey part of name stands true...

Here are the codes. ESPMH Gateway 1:
`{"admin_username":"EDIT","admin_password":"EDIT","ce_pin":16,"csn_pin":15,"reset_pin":0,"radio_interface_type":"nRF24","packet_repeats":100,"http_repeat_factor":1,"auto_restart_period":1200,"mqtt_server":"EDIT","mqtt_username":"EDIT","mqtt_password":"EDIT","mqtt_topic_pattern":"milight/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"milight/updates/:device_id/:device_type/:group_id","mqtt_state_topic_pattern":"milight/state/:device_id/:device_type/:group_id","discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":2,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"device_ids":[4369,796],"gateway_configs":[[8780,8899,6],[8907,8899,6],[925,8899,6],[796,8899,6],[788,8899,6],[8541,8899,6],[8668,8899,6],[8660,8899,6],[2143,8899,6],[2270,8899,6],[2262,8899,6],[1617,8899,5],[1744,8899,6],[1736,8899,5],[5121,8899,6],[5248,8899,6],[327,8899,6]],"group_state_fields":["state","brightness","color_temp","computed_color"]}`

ESPMH Gateway 2:
`{"admin_username":"EDIT","admin_password":"EDIT","ce_pin":16,"csn_pin":15,"reset_pin":0,"radio_interface_type":"nRF24","packet_repeats":100,"http_repeat_factor":1,"auto_restart_period":1200,"mqtt_server":"EDIT","mqtt_username":"EDIT","mqtt_password":"EDIT","mqtt_topic_pattern":"milight/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"milight/updates/:device_id/:device_type/:group_id","mqtt_state_topic_pattern":"milight/states/:device_id/:device_type/:group_id","discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":2,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":8,"device_ids":[8541,8780,796,925],"gateway_configs":[[8780,8899,6],[8907,8899,6],[925,8899,6],[796,8899,6],[788,8899,6],[8541,8899,6],[8668,8899,6],[8660,8899,6],[2143,8899,6],[2270,8899,6],[2262,8899,6],[1617,8899,6],[1744,8899,6],[1736,8899,6],[5121,8899,6],[5248,8899,6],[327,8899,6],[4369,8899,5],[0,0,5]],"group_state_fields":["state","brightness","color_temp","computed_color"]}`

Lights.yaml:
`# / Upstairs
- name: "Stairs"
  command_topic: milight/0x224C/rgb_cct/1
  state_topic: milight/updates/0x224C/rgb_cct/1
  <<: &MILIGHT_PARAMS
      platform: mqtt_json
      rgb: true
      color_temp: true
      brightness: true
- name: "Upstairs Stairs"
  command_topic: milight/0x224C/rgb_cct/1
  state_topic: milight/updates/0x224C/rgb_cct/1
  <<: *MILIGHT_PARAMS #copy of light.stairs created for floorplan multilayers
- name: "Upstairs Sofa"
  command_topic: milight/0x224C/rgb_cct/2
  state_topic: milight/updates/0x224C/rgb_cct/2
  <<: *MILIGHT_PARAMS
- name: "Upstairs Bed"
  command_topic: milight/0x224C/rgb_cct/3
  state_topic: milight/updates/0x224C/rgb_cct/3
  <<: *MILIGHT_PARAMS
- name: "Upstairs Toilet"
  command_topic: milight/0x55'55/cct/1
  state_topic: milight/updates/0x5555/cct/1
  <<: &MILIGHTCCT_PARAMS
      platform: mqtt_json
      color_temp: true
      rgb: false
      brightness: true
# Upstairs /

# Electric Room
- name: "Electric Room RGB"
  command_topic: milight/0x22CB/rgbw/1
  state_topic: milight/updates/0x22CB/rgbw/1
  <<: &MILIGHTRGBW_PARAMS
      platform: mqtt_json
      color_temp: false
      rgb: true
      brightness: true
# Electric Room /

# Garden
- platform: mqtt
  name: "Pool Light"
  state_topic: "stat/th16_/POWER"
  command_topic: "cmnd/th16_2/POWER"
  payload_on: "ON"
  payload_off: "OFF"
- name: "Spots"
  command_topic: milight/0x39D/rgb_cct/1
  state_topic: milight/updates/0x39D/rgb_cct/1
  <<: *MILIGHT_PARAMS
- name: "Patio Strip"
  command_topic: milight/0x39D/rgb_cct/2
  state_topic: milight/updates/0x39D/rgb_cct/2
  <<: *MILIGHT_PARAMS
- name: "Bale Top"
  command_topic: milight/0x39D/rgb_cct/3
  state_topic: milight/updates/0x39D/rgb_cct/3
  <<: *MILIGHT_PARAMS
- name: "Bale Strip"
  command_topic: milight/0x39D/rgb_cct/4
  state_topic: milight/updates/0x39D/rgb_cct/4
  <<: *MILIGHT_PARAMS
- name: "Garden Floods"
  command_topic: milight/0x31C/rgbw/2
  state_topic: milight/updates/0x31C/rgbw/2
  <<: *MILIGHTRGBW_PARAMS
- name: "Floodlight"
  command_topic: milight/0x1111/rgb_cct/1
  state_topic: milight/updates/0x1111/rgb_cct/1
  <<: *MILIGHT_PARAMS
- name: "Bale Front"
  command_topic: milight/0x31C/rgbw/4
  state_topic: milight/updates/0x31C/rgbw/4
  <<: *MILIGHTRGBW_PARAMS
#- name: "Patio"
#  command_topic: milight/0x215D/rgb_cct/1
#  state_topic: milight/updates/0x215D/rgb_cct/1
#  <<: *MILIGHT_PARAMS
- name: "Housings"
  command_topic: milight/0x215D/rgb_cct/2
  state_topic: milight/updates/0x215D/rgb_cct/2
  <<: *MILIGHT_PARAMS
# Garden /

# / Living
- name: "Kitchen Back"
  command_topic: milight/0x215D/rgb_cct/3
  state_topic: milight/updates/0x215D/rgb_cct/3
  <<: *MILIGHT_PARAMS
- name: "Patio Bench"
  command_topic: milight/0x215D/rgb_cct/4
  state_topic: milight/updates/0x215D/rgb_cct/4
  platform: mqtt_json
  color_temp: true
  rgb: true
  brightness: true
  brightness_scale: 75
#- name: "Kitchen Side"
#  command_topic: milight/0x21DC/rgbw/1
#  state_topic: milight/updates/0x21DC/rgbw/1
#  <<: *MILIGHTRGBW_PARAMS
#- name: "Living"
#  command_topic: milight/0x21DC/rgbw/2
#  state_topic: milight/updates/0x21DC/rgbw/2
#  <<: *MILIGHTRGBW_PARAMS
- name: "Backside"
  command_topic: milight/0x21DC/rgbw/4
  state_topic: milight/updates/0x21DC/rgbw/4
  <<: *MILIGHTRGBW_PARAMS
- platform: limitlessled
  retain: true
  bridges:
  - host: 192.168.86.90
    groups:
    - number: 1
      type: rgbw
      name: Kitchen Side
    - number: 2
      type: rgbw
      name: Living
# Living /

# / Master
- name: "Master Bedroom"
  command_topic: milight/0x85F/rgb_cct/1
  state_topic: milight/updates/0x85F/rgb_cct/1
  <<: *MILIGHT_PARAMS
- name: "Master Mirror"
  command_topic: milight/0x85F/rgb_cct/2
  state_topic: milight/updates/0x85F/rgb_cct/2
  <<: *MILIGHT_PARAMS
- name: "Master Shower"
  command_topic: milight/0x85F/rgb_cct/3
  state_topic: milight/updates/0x85F/rgb_cct/3
  <<: *MILIGHT_PARAMS
- name: "Master Toilet"
  command_topic: milight/0x85F/rgb_cct/4
  state_topic: milight/updates/0x85F/rgb_cct/4
  <<: *MILIGHT_PARAMS
- platform: mqtt
  name: "Master Dressing"
  state_topic: "stat/th16_1/POWER"
  command_topic: "cmnd/th16_1/POWER"
  payload_on: "ON"
  payload_off: "OFF"
# Master /

# / Kids
- platform: limitlessled
  bridges:
  - host: 192.168.86.93
    groups:
    - number: 1
      type: bridge-led
      name: Noa LED
#  - host: 192.168.86.94
#    groups:
#    - number: 1
#      type: bridge-led
#      name: Luke LED
- name: "Kids Moonman"
  command_topic: milight/0x1401/rgb_cct/1
  state_topic: milight/updates/0x1401/rgb_cct/1
  <<: *MILIGHT_PARAMS
- name: "Kids Toilet"
  command_topic: milight/0x1401/rgb_cct/2
  state_topic: milight/updates/0x1401/rgb_cct/2
  <<: *MILIGHT_PARAMS
- name: "Kids Mirror"
  command_topic: milight/0x1401/rgb_cct/3
  state_topic: milight/updates/0x1401/rgb_cct/3
  <<: *MILIGHT_PARAMS
- name: "Kids Shower"
  command_topic: milight/0x6D0/rgbw/1
  state_topic: milight/updates/0x6D0/rgbw/1
  <<: *MILIGHTRGBW_PARAMS
# Kids /

# / Street
- name: "Street 1"
  command_topic: milight/0x314/cct/1
  state_topic: milight/updates/0x314/cct/1
  <<: *MILIGHTCCT_PARAMS
- name: "Street 2"
  command_topic: milight/0x314/cct/2
  state_topic: milight/updates/0x314/cct/2
  <<: *MILIGHTCCT_PARAMS
- name: "Street RGB"
  command_topic: milight/0x31C/rgbw/1
  state_topic: milight/updates/0x31C/rgbw/1
  <<: *MILIGHTRGBW_PARAMS
# Street /
`

I've rid the codes of optional entries like Effects, QOS or Retain in an effort to troubleshoot.

And the actual HA interface rendering:
![no color-2](https://user-images.githubusercontent.com/35156237/35595226-eba7cd18-0650-11e8-9f51-88fdbddab315.jpeg)
![no color](https://user-images.githubusercontent.com/35156237/35595237-f0e2bfe0-0650-11e8-8e6a-1b9e5f4cff00.jpeg)

Thanks to all the participants in this thread, I hope we find my mistake.

**Comment by MimbaMonkeyHouse** [comment]
Well, that was easy! This solved my issue. I was sure I read somewhere that updates should now be used as a topic instead of state.
Thanks to @gramck for enacting a quick solution and to @sidoh for a great integration... Maybe updating the docs could help. Let me know if help is needed.
![color](https://user-images.githubusercontent.com/35156237/35596570-659e22b2-0655-11e8-942f-5191c5d723dd.jpeg)

**Comment by sidoh** [comment]
Thanks, @garmck!  Good catch.

@MimbaMonkeyHouse, you're right, the wiki page was outdated.  I updated it.

There's more info on the difference between the update and state topics here:

https://github.com/sidoh/esp8266_milight_hub#updates

**Comment by sidoh** [comment]
Sounds like this is resolved, but please feel free to reopen if not.
