### ISSUE TITLE
Bulbs don't match published states if changes made with remote when turned (soft) off

### ISSUE THREAD

**Issue by Skinah** [sidoh/esp8266_milight_hub#232]
To reproduce this bug:

Use milight remote and turn brightness to full.
Use milight remote and turn off globe.
Use milight remote and turn brightness to any value besides full.
MQTT states show it is off and the new brightness was detected correctly.
Use milight remote and turn globe on.

Fault = Globe is not at the brightness that was set whilst the globe was off. State displayed with MQTT broker does not match the real state of the globe.

Suggest that the states do not get updated/published to MQTT when the globe is off.

Not a big deal but the controls in OpenHab end up not matching what the globes state is which is not ideal. When the globe is turned on, the hub sends via MQTT that the globe is on and the level should be X value when the globe is actually at Y value.

Hope this report is clear and makes sense, and as always thanks for the work done on this.

I use rgb_cct globes and actually use LEVEL and not brightness in the state in case this info is needed.

**Comment by sidoh** [comment]
Thanks @Skinah, great catch.

I think your first suggestion is the correct approach:

> Suggest that the states do not get updated/published to MQTT when the globe is off.
