### ISSUE TITLE
Mireds

### ISSUE THREAD

**Issue by diabl0w** [sidoh/esp8266_milight_hub#236]
Using values in mireds (via color_temp in mqtt) results in reverse temperatures. The expected behavior of a mired value of 370 should be a cool blue light, and a mired value of 157 should be a warm orange light. 
Instead, the behavior of a value sent at 370 is a warm white and a value at 157 is a cool white.

Essentially, the range is backwards

EDIT: thank you so much for this project by the way, it has saved me hundreds of dollars from having to by phillips hue bulbs

EDIT: nevermind im bad at math

**Comment by sidoh** [comment]
I've done the same thing a bunch of times with white temperature stuff.  The fact that "warm" temperatures have lower kelvin values throws me off.  Mireds actually make more sense intuitively :)

Glad you've found it useful.
