### ISSUE TITLE
General future request (like software WDT)

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#24]
Maybe add to library software WDT (and maybe add this option in Web UI)? For example, On, Off, sec for restart (0-xxx)?

**Comment by sidoh** [comment]
I'm not familiar with the acronym WGT. Can you tell me what it means?

**Comment by Lstt2005** [comment]
WDT, of course :)

**Comment by sidoh** [comment]
Haha. What is WDT? I promise I'm not trying to be dense :)

**Comment by Lstt2005** [comment]
:) WatchDogTimer - in ESP - ESP.restart() restarts the CPU. https://github.com/esp8266/Arduino/blob/d2b370b22d1593226fad3ae82d7feac795dfb51d/doc/libraries.md
Because ESP8266 NOT stable device sometimes:)

**Comment by sidoh** [comment]
Gotcha. So the idea is to provide a way to restart the ESP via an API, and also maybe a way for regular restarts (like restart every 24 hrs or something)?

**Comment by Lstt2005** [comment]
Yes I agree. But for beginners, I think that it would be very convenient if such an automatic restart possible with the indication of a time interval or in the UI, or the parameter setting via the API (min, hours, etc.) would be realized..

**Comment by sidoh** [comment]
Sure, makes sense. If we added it to the API, of course makes sense to expose it in the UI as well.

So I'm imagining a command to force a reset, and an optional setting to schedule a reset every X minutes. Obviously would find a way to incorporate both of those things into the UI as well.

Does that sound in line with what you're imagining?

**Comment by sidoh** [comment]
I added a setting for auto restarts and a restart button in the v1.1.0 branch.

**Comment by Lstt2005** [comment]
Ok, thank! Today i test it.

**Comment by sidoh** [comment]
Sweet!

Did this get at everything you had in mind?

**Comment by Lstt2005** [comment]
For now, i don't new ideas. Thanks.

**Comment by sidoh** [comment]
Sweet. Thanks for the idea! :)
