### ISSUE TITLE
Support for MiLight FUT039

### ISSUE THREAD

**Issue by francescofact** [sidoh/esp8266_milight_hub#242]
Hi, 
i can't link the led rgbww strip controller with the mi light hub esp8266.
I think because it's not supported. Please add it

**Comment by sidoh** [comment]
It is supported.  It uses the RGB_CCT remote type.

If you're having trouble, please read through this: https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting

Feel free to open another ticket if you're still having trouble.

**Comment by NicoBijl** [comment]
If it is supported, please add it to the readme? 

Thanks!
