### ISSUE TITLE
Is the beta PlatformIO still required?

### ISSUE THREAD

**Issue by cmidgley** [sidoh/esp8266_milight_hub#244]
In the README, it says: 

> Note that currently you'll need to use the beta version of PlatformIO. To install with pip:
> pip install -U https://github.com/platformio/platformio-core/archive/develop.zip

I found that I was successful with the standard/production version of PlatformIO.  Perhaps we should remove this from the README?

**Comment by sidoh** [comment]
Yeah, looks like they released a version that had the needed feature.

Actually looks like the esp8266/Arduino folks released 2.4, which had the feature (KRACK bugfix) that I needed pio beta for anyway.

Great catch!

**Comment by jstans** [comment]
The milight gateways being susceptible to KRACK is part of the reason I ended up here and haven't set up an isolated subnet. Out of interest, is the comment you made in the README.md regarding 2.4ghz being insecure related to this @sidoh ? (and thus no longer relevant?)

**Comment by sidoh** [comment]
The comment in the README is referring to the 2.4 GHz communications sent to the bulbs, not Wifi.  The packets are completely unsecured and trivial to spoof.
