### ISSUE TITLE
Is my light supported?

### ISSUE THREAD

**Issue by olskar** [sidoh/esp8266_milight_hub#248]
Hello!

I am trying to pair my bulb with the milight hub but I can not get it to work.

Earlier I used Rflink that was able to pair the light by sending the command:
10;MiLightv1;20F746;01;34BC;PAIR;

So I know both the bulb and sender is working fine.

Is there a way to see if my bulb is supported or not? It is a RGB+CCT - aka RGBWW

**Comment by rjsachse** [comment]
Looks like yes your globe is supported. Have you used the sniffer or try to pair a bulb to say 0x123A

**Comment by rjsachse** [comment]
Have you read https://github.com/sidoh/esp8266_milight_hub/wiki/Pairing-new-bulbs

**Comment by olskar** [comment]
Thanks, redid everything with another esp8266 :) now works!

**Comment by sidoh** [comment]
Thanks, @rjsachse!

Glad you got it working, @olskar.
