### ISSUE TITLE
Wrong group number sent if you change from fut089 to another remote type

### ISSUE THREAD

**Issue by Skinah** [sidoh/esp8266_milight_hub#256]
To reproduce:

in the control panel of the hub select fut089 remote type and a group number above 4, eg group 7
press another remote type for example rgbcct
move any control and the MQTT messages/states show the hub is now still using group 7 with a remote type that does not allow this.

Suggestion: Probably easiest to default the group to 1 each time a new remote type is selected if the group is above 4.

**Comment by sidoh** [comment]
Thanks, good catch.

**Comment by sidoh** [comment]
Should be fixed in afb1e27569de08123708952c41aedc6d63a5e90a
