### ISSUE TITLE
FUT013 Support ?

### ISSUE THREAD

**Issue by clovisdivay** [sidoh/esp8266_milight_hub#262]
Hi, I followed all the steps and got the Web UI running, but I cannot get to pair my bulbs...
The model is FUT013, a E14 base RGB+CCT LED bulb.
http://futlight.com/productdetails.aspx?id=137&typeid=101

It says on your page that it is easy to add support, can you help me with that ?
Thanks.

**Comment by sidoh** [comment]
Those bulbs should work with the RGB+CCT remote type.  If it's not working for you, please read through the troubleshooting guide:

https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting

**Comment by clovisdivay** [comment]
Okay, my wiring was off. I chose the wrong GPIO pin for the CE.
Thanks !
