### ISSUE TITLE
Webpage intermittently appears blank in 1.7.0-dev7 on Android Chrome

### ISSUE THREAD

**Issue by sidoh** [sidoh/esp8266_milight_hub#264]
When this happens, the following seems to fix it (no idea why):

* Set "Request Desktop" to true
* Refresh
* Page now shows
* Can turn "Request Desktop" to false, page will still load

**Comment by cmidgley** [comment]
I do have some tricky CSS to keep the button bar at the bottom - I wonder if that is doing this?  I don't have Android (though maybe I can download an emulator, but have not tried).   Maybe try removing all of this:

```
body {
  margin-bottom: 200px;
}
footer {
  height: 200px;
}
@media only screen and (min-width : 320px) {
  body {
    margin-bottom: 250px;
  }
  footer {
    height: 250px;
  }
}
@media only screen and (min-width : 480px) {
  body {
    margin-bottom: 200px;
  }
  footer {
    height: 200px;
  }
}
@media only screen and (min-width : 768px) {
  body {
    margin-bottom: 158px;
  }
  footer {
    height: 158px;
  }
}
@media only screen and (min-width : 992px) {
  body {
    margin-bottom: 116px;
  }
  footer {
    height: 116px;
  }
}
footer {
  position: absolute;
  bottom: 0;
  width: 100%;
  background-color: rgba(41,41,45,.9);
  padding-top: 20px;
}
footer .btn {
  margin-bottom: 10px
}
```
If it works, we will either need to try to debug why Android can't render this, or change the styling to not push these buttons to the bottom (they could just scroll, which I didn't think looked as much like an "app" as this design ... or maybe we switch to menus after all!)

I'm heading off on a short trip, so won't be able to look into this for a bit.  If somebody else tries it, I'm all ears on what happens!

**Comment by sidoh** [comment]
Hm, could be.  What's confusing is that it seems transient.  I can't even manage to reproduce it now.  I'm going to rejigger the navigation.  Hopefully we'll able to move off of the absolute positioning.

**Comment by sidoh** [comment]
@southwalesboy, @rjsachse are either of you able to reproduce using [1.7.0-dev8](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.7.0-dev8)?  I haven't seen it again yet.

**Comment by rjsachse** [comment]
Still have trouble with latest version.
Maybe a chrome issue. On my rpi using chromium still won't load page, down the bottom say's "waiting for gitcdn.github.io..."
Don't work on android chrome either (latest version) i installed firefox and it works but seems the sniffing don't work. I have tried Desktop Site "ticked" cleared cache and website settings.

It works on my old s2 phone with a older version of chrome on it. Very puzzling.

**Comment by sidoh** [comment]
Huh, while playing around I just saw this again.  It went away when I refreshed.

I can reproduce it fairly reliably with a fresh incognito window.  This makes me think it's interacting with the cache somehow.

As best I can tell, this error occurs when the content length doesn't match the content the server sends.  I'll take a closer look later.

**Comment by rjsachse** [comment]
For got about trying incognito mode.

**Comment by sidoh** [comment]
Alright, definitely something funky.  curl is whining as well:

```
curl: (18) transfer closed with outstanding read data remaining
```

I'm poking at it now.

**Comment by sidoh** [comment]
Okay, I think this fixes it: 3c2e8169ccb366f2b5f8a4d26714d5fbf2634dc1.

@rjsachse, could you try with the latest 1.7 code?  I can release a new tag if you need a pre-compiled binary.

**Comment by sidoh** [comment]
Released [1.7.0-dev9](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.7.0-dev9) with a fix.  Seemed important enough for its own tag :)

**Comment by sidoh** [comment]
@cmidgley, no idea why we hadn't seen this before.   Think it was a server-side error.  Perhaps the webpage passed some threshold where the server started sending output in more than one chunk, meaning `Content-Length` became inaccurate.

**Comment by FrankZZ** [comment]
I've updated via OTA to `1.7.0-dev9` but I still get a blank page in Chrome v66 on macOS, also in incognito mode. (a GET to /about shows version `1.7.0-dev9`)

Error in network tab on root path: `ERR_INCOMPLETE_CHUNKED_ENCODING`

**Comment by sidoh** [comment]
Rats.  Can you try `curl`ing?

**Comment by FrankZZ** [comment]
```$ curl http://192.168.1.119
[truncated]
curl: (18) transfer closed with outstanding read data remaining
[truncated]```

**Comment by sidoh** [comment]
Huh.  That definitely went away when I updated to dev9.  I'll take another look later today.

**Comment by sidoh** [comment]
Okay, I think this is for reals fixed by @FrankZZ in #271.  Thanks FrankZZ!

**Comment by sidoh** [comment]
Pulled into [1.7.0-dev10](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.7.0-dev10).

**Comment by olskar** [comment]
Fixed for me at least in dev10

**Comment by rjsachse** [comment]
Wow thank you all, thinking i was going on going insane. It now works on rPi chromium  and latest version of Android Chrome on old and newer phone with different screen sizes.

BUT: I stil have a error with sniffing traffic on my Samsung Note 4.

Works on rPi Chromium, Samasung S2 for sniffing traffic, so seems to be a bug there.

The bottom bubble appears showing packets sniffed but no packets are shown but do on other devices and platforms

**Comment by sidoh** [comment]
Probably an old browser thing.  Does it work with 1.6?

**Comment by rjsachse** [comment]
No it doesn't work with 1.6.0 upwards. Not sure if it ever did work on this phone. Not a huge deal unless others complain about it either but does work on desktop chromium. Not like i need the feature until i buy another  remote and have 2 other devices that i can use.
