### ISSUE TITLE
Some question about UDP  v6 and support MiLight 3.0

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#27]
As i write earlier, i found github Android project Bilight - https://github.com/JasperG/bilight
When i experiment with it, sometimes, i see this messages in ESP8266 console:
"
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
Received request with untracked session ID: 0
"
Sometimes be, sometimes no. Question - is it application problem or some bug in ESP8266 library?
![30-03-2017 112500](https://cloud.githubusercontent.com/assets/6728198/24494779/c831d4c0-153b-11e7-8d85-38fa8582d0a3.jpg)

**Comment by sidoh** [comment]
That means the app is sending a command with a session ID the ESP doesn't recognize. Sessions are only important in order for the ESP to know which IP and port to send a response packet to. If the app works well without response packets, it shouldn't matter.

This could happen if, for example, the app was started and then the ESP was rebooted. The app should probably handle getting a new session, but looks like maybe it's not.

**Comment by Lstt2005** [comment]
Ok, i see.

**Comment by Lstt2005** [comment]
It's work situation, when some server with different ID work on one UDP port?
![30-03-2017 114226](https://cloud.githubusercontent.com/assets/6728198/24495498/000db2cc-153e-11e7-931d-5bf54a0ac414.jpg)

**Comment by sidoh** [comment]
That wouldn't work, no. There has to be a way to select a device ID, and the UDP protocol doesn't expose a way for that to happen. So you gotta go off of something like the port.

**Comment by Lstt2005** [comment]
I have a great desire to experimet with Bilight and want control more, than 1 ID with the same port. Can we try enter multiple Device ID in Gateway Servers?

**Comment by sidoh** [comment]
I guess I mean to say that as far as I know, there is literally not a way to do this within the confines of the official UDP protocol.

**Comment by Lstt2005** [comment]
You did not understand me a little. I mean, if you can add more than one ID function to the library, if there are more, then send several packets to other stored IDs

**Comment by sidoh** [comment]
Hmm, I see. I guess this feels a little unclean to me, but I'm not sure why. I guess maybe because it seems like clients ought to be able to address a specific identifier directly.

**Comment by Lstt2005** [comment]
Although, perhaps you're right! In fact, nothing prevents you from pair a virtual ID to an unlimited number of devices and managing them via UDP.

**Comment by Lstt2005** [comment]
Today try new branch - discovery - work! :)
Sending response to 192.168.0.119:52123
[MiLightUdpServer port 5987] - Handling packet: D0 00 00 00 02 00 02
Packet size: 7
Sending response to 192.168.0.119:52123
[MiLightUdpServer port 5987] - Handling packet: D0 00 00 00 02 00 02
Packet size: 7
Sending response to 192.168.0.119:52123
[MiLightUdpServer port 5987] - Handling packet: D0 00 00 00 02 00 02
Packet size: 7
Sending response to 192.168.0.119:52123
[MiLightUdpServer port 5987] - Handling packet: D0 00 00 00 02 00 02
Packet size: 7
Sending response to 192.168.0.119:52123

**Comment by sidoh** [comment]
:) awesome

**Comment by Lstt2005** [comment]
one question - if i try new china LEDs - can i implemet new sync words or different packet size..?
I mean this - https://detail.1688.com/offer/522143371857.html 
![31-03-2017 204248](https://cloud.githubusercontent.com/assets/6728198/24562273/dc3674a4-1652-11e7-8eeb-e48071fda1df.jpg)

**Comment by sidoh** [comment]
Yeah, I think it probably is a knockoff or redistributor of MiLight. I have no way of knowing for sure, though.

It's pretty easy to add different syncwords and packet structures at this point, so if it does need that, easy enough to add.

**Comment by Lstt2005** [comment]
Ok, i must receive within 1 mouth, and try it.

**Comment by Lstt2005** [comment]
MiLight 3.0 Work!
![photo_2017-03-31_23-12-09](https://cloud.githubusercontent.com/assets/6728198/24567729/a15f4bac-1667-11e7-96dc-eaad17008321.jpg)
![photo_2017-03-31_23-11-30](https://cloud.githubusercontent.com/assets/6728198/24567744/abccedce-1667-11e7-83e6-2af595a6b1fb.jpg)
But, as I wrote earlier, adjusting the color temperature works the other way around.

**Comment by sidoh** [comment]
Yeah I was noticing that too. I basically chose the direction that seemed to match the choice made by the folks who worked on MiLight stuff for HomeAssistant. It's clear this is flipped from the official MiLight app, though. I just pushed a fix.

**Comment by sidoh** [comment]
The white temperature ordering should be correct in the latest dev release. 

Did we answer all the questions you had for this ticket?

**Comment by Lstt2005** [comment]
No, thanks!

**Comment by sidoh** [comment]
👍
