### ISSUE TITLE
Cannot set wifi parameters because of broken webpage on 1.7.0-dev10

### ISSUE THREAD

**Issue by bombcheck** [sidoh/esp8266_milight_hub#273]
Starting with a new, clean flash I am unable to set wifi parameters because of broken web page.
Seems the page requires external JS-libs but can not load them because in this state, the device which I use to configure the hub has no internet connection (it is connected to the hubs access point).

Using a desktop computer with a wifi- and a wired network connection works (when manually configuring the wifi adapter because otherwise the gateway points to the hubs access point which results in no internet).

**Comment by bombcheck** [comment]
Strange... The WiFiManager should come up in this state... After another power cycle it works (WifiManager shows up when no WiFI is configured). But at first boot after flashing I got the hubs webpage at 192.168.4.1...

**Comment by sidoh** [comment]
WifiManager times out after 3 minutes.  When this happen looks like it just falls through to normal operation except in AP mode.

I think it should probably reset itself if connection fails.
