### ISSUE TITLE
Control saturation in Home Assistant

### ISSUE THREAD

**Issue by kurniawan77** [sidoh/esp8266_milight_hub#274]
Hi,

How should i configure Home Assistant to control the saturation for RGB+CCT?
This is what i have configured.

![image](https://user-images.githubusercontent.com/3305888/39619279-909ec61c-4f87-11e8-982b-6be4c453dbd6.png)
and
![image](https://user-images.githubusercontent.com/3305888/39619303-a700fad8-4f87-11e8-992e-394cbacf3ebf.png)

Or must i have something else then white_value?

Regards

**Comment by sidoh** [comment]
You can't control saturation from HASS directly, at least not with the `mqtt_json` component.  RGB should expose a color wheel, which will adjust both hue and saturation appropriately behind the scenes:

![image](https://user-images.githubusercontent.com/589893/39619454-bd38e130-4f3c-11e8-816d-c7c892752329.png)

If you want to control it directly you'll have to write your own HASS component.

**Comment by kurniawan77** [comment]
Thanks for the very very fast reply! The color wheel will do it fine too!
