### ISSUE TITLE
FUT-091 Pair not work..

### ISSUE THREAD

**Issue by itProfi** [sidoh/esp8266_milight_hub#281]
Hello all!
When i try pair controller with new code in controller via HTTP, when i push pair - nothing happing..Unpair function work wel..
Chris! Do you plan add group buttons in FUT-091 remote?
And lst thing - can you change Color Teperature slider (invert it)?

**Comment by sidoh** [comment]
Can you try this branch?

https://github.com/sidoh/esp8266_milight_hub/tree/fut091_support

**Comment by itProfi** [comment]
Yes, of course!

**Comment by sidoh** [comment]
@itProfi any luck with the FUT091 branch?

**Comment by itProfi** [comment]
Yes, it's work!
