### ISSUE TITLE
Auto-save entered device IDs

### ISSUE THREAD

**Issue by itProfi** [sidoh/esp8266_milight_hub#282]
Version 1.7.0 with fut_091_support. When i put in field ane correct Device id - it Entered, but not saved...
When i put manually Device id in Dec format in settings.json - and restore it - all works fine..
![18-05-2018 193804](https://user-images.githubusercontent.com/6728198/40246933-4ebf280c-5ad3-11e8-8183-f404010dc040.jpg)
![18-05-2018 193540](https://user-images.githubusercontent.com/6728198/40246934-4edfe7ea-5ad3-11e8-8d47-b6ddd7bafcda.jpg)

**Comment by bombcheck** [comment]
Yeah noticed that, too. With older version you had to submit setting (bottom of page) the save the device id. With new version just click on "Settings" and then on "Submit".

**Comment by sidoh** [comment]
Yep, @bombcheck is right.  Have to save the settings.

No reason for it to not auto-save, though.  We can leave this ticket open for that feature

**Comment by QuagmireMan** [comment]
I am having the same issue, but even going into the settings and pressing submit does not solve the issue.
