### ISSUE TITLE
Group 0 packets should not clobber state for individual groups

### ISSUE THREAD

**Issue by sidoh** [sidoh/esp8266_milight_hub#284]
## Summary

When a packet for group 0 is received, we update the state for group 0, and then overwrite the states for individual groups.

Instead, the incremental update should be applied to each of the individual groups, and group 0 should not have a state (it's meaningless since it's a "virtual" group).

## Notes

* [x] Apply group 0 increments to individual groups, rather than overwriting with group 0 state.
* [x] ~We should still have an option to send MQTT states for group 0~.  Group 0 state should not be persisted.  It's confusing.
* [x] ~We should consider adding an option to send fanned out MQTT states.  While this is heavy-weight, the alternative is to force users to merge states themselves, which is also not ideal.~ Considered.  Not going to do this.  Too heavy.

#### Initialize state to "on" and brightness to max for virtual group 0
```
$ curl -H 'content-type: application/json' -X PUT -d '{"status":"on","level":100}' 10.133.8.158/gateways/1235/rgbw/0
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}%

$ curl 10.133.8.158/gateways/1236/rgbw/\{1,2,3,4\}

[1/4]: 10.133.8.158/gateways/1236/rgbw/1 --> <stdout>
--_curl_--10.133.8.158/gateways/1236/rgbw/1
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}
[2/4]: 10.133.8.158/gateways/1236/rgbw/2 --> <stdout>
--_curl_--10.133.8.158/gateways/1236/rgbw/2
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}
[3/4]: 10.133.8.158/gateways/1236/rgbw/3 --> <stdout>
--_curl_--10.133.8.158/gateways/1236/rgbw/3
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}
[4/4]: 10.133.8.158/gateways/1236/rgbw/4 --> <stdout>
--_curl_--10.133.8.158/gateways/1236/rgbw/4
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}%
```

#### Set brightness to 10% for group 1
```
$ curl -H 'content-type: application/json' -X PUT -d '{"status":"on","level":10}' 10.133.8.158/gateways/1236/rgbw/1
{"state":"ON","brightness":31,"color":{"r":255,"g":255,"b":255}}%
```

#### Turn group 0 on (notice we're not setting brightness)
```
$ curl -H 'content-type: application/json' -X PUT -d '{"status":"on"}' 10.133.8.158/gateways/1236/rgbw/0
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}%
```

#### State for group 1 is clobbered by group 0 state
```
$ curl 10.133.8.158/gateways/1236/rgbw/1
{"state":"ON","brightness":255,"color":{"r":255,"g":255,"b":255}}%
```

**Comment by boaschti** [comment]
Hi, great work. Can you built .bin?

**Comment by sidoh** [comment]
Sure.  Let me get the FUT091 support merged as well first.  Should have time this weekend.  If not I'll release a version with just this fix.

**Comment by sidoh** [comment]
Tagged 1.8.0-dev1 with this fix.  Travis should publish the binaries shortly
