### ISSUE TITLE
sonoff

### ISSUE THREAD

**Issue by agoralive** [sidoh/esp8266_milight_hub#286]
Hi

Is there a waz to use the sonoff TH10 with this build?

I have a few of these which have been "modified" with the Tasmota script, and I would like to use these perhaps for my Mi-Light system....?

**Comment by sidoh** [comment]
The only real difference in the builds is that they're compiled for different flash sizes.  nodemcuv2 and d1_mini are pretty much interchangeable, for example.

As long as your chip has SPI pins exposed, and you can attach an nrf24l01, you should be able to use one of the existing builds.

If it has 4 MB flash, d1_mini should work.  If 1 MB, esp07 should work.

**Comment by sidoh** [comment]
Going to close, but feel free to reopen if you feel like your question wasn't addressed.
