### ISSUE TITLE
fut_091 branch mqtt not accept kelvin commnad...

### ISSUE THREAD

**Issue by itProfi** [sidoh/esp8266_milight_hub#291]
When i try control my fut-035 controller (with b2/fut091 remote), when i send in topic "milight/1/fut091/1" command "{"status":"ON","brightness":254,"color_temp":152}" it's work fine..
When i send in topic "milight/1/fut091/1" command "{"status":"ON","brightness":254,"kelvin":0}" it's not work...
I guess, that command "kelvin" not work..
And it's work with brightness range 1-254 and color_temp 152-369

**Comment by sidoh** [comment]
`kelvin` is not a supported command.  I think `temperature` is probably what you're looking for.

Documentation on supported command keys here: https://github.com/sidoh/esp8266_milight_hub#bulb-commands
