### ISSUE TITLE
Feature request: Auto-restart device on selected intervals

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [sidoh/esp8266_milight_hub#292]
I know this can be done via curl commands, but I believe it would be nice to add such a setting directly from the UI. Device could be set to restart on set intervals, say every 3 hours.
The gateway is much more stable since the latest versions, but I'm still experiencing locks when sending multiple commands to multiple bulbs.

**Comment by devax** [comment]
Check out "Settings" -> "Setup" -> "Auto-restart period".

**Comment by sidoh** [comment]
Oops, sorry for the late reply.

@devax is right (thanks for replying, devax!).  This is already a feature.

**Comment by MimbaMonkeyHouse** [comment]
Aha, sorry guys. Thanks a lot for letting me know!
