### ISSUE TITLE
Range on FUT103

### ISSUE THREAD

**Issue by alekslyse** [sidoh/esp8266_milight_hub#296]
This might be a bit bulb specific compared to software fault, but not sure. I setup the software on a nodeMCU with a NRF24L01+PA+LNA SMA (The one with antenna).

It works great with the  FUT014 bulbs (regular round bulbs), but with the FUT103 (GU10) I cant get any range out of it. The FUT014 works with no issues outside the house (about 20m from the ESP), and the FUT103 is 1m away from them, refusing to do anyting. Moving them 1-2m from the ESP they work.

Anyone else with some thoughts about range and FUT103?

Some info:

{"admin_username":"","admin_password":"","ce_pin":16,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"192.168.1.70","mqtt_username":"","mqtt_password":"","mqtt_topic_pattern":"milight/:device_id/:device_type/:group_id","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"milight/states/:device_id/:device_type/:group_id","discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":3,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":20,"enable_automatic_mode_switching":true,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"On","led_mode_operating":"Slow blip","led_mode_packet":"Flicker","led_mode_packet_count":3,"device_ids":[1,2,3,4,5,6,7,8,9,3119],"group_state_fields":["state","brightness","mode","color_temp","bulb_mode","computed_color"]}

{"version":"UNKNOWN","variant":"huzzah","free_heap":20720,"arduino_version":"2_4_1","reset_reason":"External System"}

**Comment by sonicnkt** [comment]
I have a few FUT103 and i noticed something similiar but not as bad as yours.
They work fine with the nodemcu board 7-10m away and in another room but i have to add that i have no brick walls in my apartment. 
Putting the hub in the center of my flat works fine to controll everything here (85m²).

i could imagine that the range also gets influenced by the gu10 lamp/socket. If its a full metal housing that covers the whole bulb with only the front exposed it could be worse?

**Comment by sidoh** [comment]
Do your FUT103s work better with official milight devices?

You could try cranking up the number of repeats, but probably shouldn't be necessary.

**Comment by sidoh** [comment]
Gonna close because it seems unlikely that it's a software issue.  But please feel free to re-open if you have data that suggests otherwise.
