### ISSUE TITLE
NRF Power Settings

### ISSUE THREAD

**Issue by Markus1970** [sidoh/esp8266_milight_hub#298]
Hi,

I had added an issue few month ago regarding the power issues when an amplified NRF24L01 is in use.
The Problem was that the power settting was hard coded to MAX. While every send cycle the Module reboots. I have changed then the power Settings to min and everything was wroking fine. But i cannot find this post anymore :-(
Want to do itwith the latest Version in the source Code but i don't remember where it was to find.
Can somebody help me there and can tell me in which partof the source was the power setting defined?
By the way can this also be implemented somewhere in the next Releases? Any possibilty to Change the power Settings via the WebUI ?

Many thanks

Markus

**Comment by sidoh** [comment]
I think it's #208?

Yeah, definitely want to get around to adding this.  Just a matter of plumbing in the settings.  Don't have a ton of slack time for this project right now, but that'll change eventually :)
