### ISSUE TITLE
Pair issue

### ISSUE THREAD

**Issue by tr1pp4** [sidoh/esp8266_milight_hub#303]
I did try to pair my FUT103 bulbs according to: 
https://github.com/sidoh/esp8266_milight_hub/wiki/Pairing-new-bulbs
But nothing happens

Sniffing works well, so my build seems to work.

Thank you for any advice

**Comment by sidoh** [comment]
Please work through the troubleshooting guide here:

https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting

It's likely that your nRF24L01 is defective.  Feel free to reopen if you have additional questions.
