### ISSUE TITLE
changing colors in HA not working in 1.8.0

### ISSUE THREAD

**Issue by EdgardosReis** [sidoh/esp8266_milight_hub#312]
Hello Chris,
when I try to change the color in Home Assistant with the version 1.8.0 nothing happens. I have it configured as MQTT Lights and when I change the color a message like this is published:
{"state": "ON", "color": {"r": 0, "g": 0, "b": 255}}
However, if the bulb is already ON, the message is ignored. It seems that is ignoring the commands when the "state" is the same. If I publish a message like {"color": {"r": 0, "g": 0, "b": 255}} it works.
This doesn't happen with the version 1.7.1.
of course, I'm talking about changing colors but the same behavior to changing temperature or brightness.

Best Regards.

**Comment by sidoh** [comment]
Hi Edgar,

Can you tell me a little more about your setup?

* What remote type are you using? (RGB, RGB+CCT, etc)
* What group is your device bound to?
* What version of HASS are you on?

**Comment by sidoh** [comment]
Fixed in 1.8.1, I hope (working for me, at least :) --

https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.8.1

**Comment by EdgardosReis** [comment]
Yes! Working now for me too. Thank you!
