### ISSUE TITLE
Sniffer work paring the device ID not

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#317]
Hi,

I can sniffer the bulbs ID. But when a add the ID and want pair them nothing happen.
All wire are correct connect. 

Firmware: 1.8.1
NodeMCU v3 with CH34* circled
NRF24L01+

**Comment by sidoh** [comment]
Bulbs don't have IDs.  Do you mean that you can sniff a remote's ID?

Are the bulbs already paired with the remote?

**Comment by poudenes** [comment]
Hmm I entered the ID that's shown in sniffer log but when I want control it nothing happens with the bulbs.

**Comment by sidoh** [comment]
It sounds like a hardware defect.  Please read through this guide:

https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting

**Comment by poudenes** [comment]
Checked it out. Got ID numbers. And was trying to test them. Suddenly find out that the given ID will switch on/off a total different bulb in the house. So send/receive work. But now have to find out what ID link to what bulb.

When i add a ID and refresh the page the added device id's are gone. IS that normal?

**Comment by sidoh** [comment]
Depends on your definition of "normal," lol.

https://github.com/sidoh/esp8266_milight_hub/issues/282

shouldn't work that way, but currently does.

**Comment by sidoh** [comment]
Going to close because it seems like this is resolved, but please feel free to reopen if that's not the case.
