### ISSUE TITLE
worked once and not able to connect next time

### ISSUE THREAD

**Issue by titusece** [sidoh/esp8266_milight_hub#321]
Hello,
I have referred the below document to make use of ESP8266 as hub to control the milight bulb.
https://blog.christophermullins.com/2017/02/11/milight-wifi-gateway-emulator-on-an-esp8266/
And I have ordered couple of milight bulbs, nodemcu boards and NRF24+ modules and did the steps mentioned in the link, reached to UI webpage now.

https://github.com/sidoh/esp8266_milight_hub/wiki/Pairing-new-bulbs
By referring this doc, I'd set unique id in webpage and trying to pair with bulb, but one time I was able to pair and able to control the colors of the bulb, but afterwards I am not able to connect/pair.
Looks like stability issue, what is causing for this issue ?
Thanks for the help.

**Comment by sidoh** [comment]
Hi,

Keep in mind that you only need to pair once.  Pairing is a command that tells a bulb in pairing mode (typically the first 5s after it's powered on) to associate itself with a provided ID.

Once paired, the bulb stores that ID and responds to commands sent for that ID.

**Comment by sidoh** [comment]
Going to close, but feel free to reopen if you have further questions.
