### ISSUE TITLE
NRF24L01+PA+LNA

### ISSUE THREAD

**Issue by Streep** [sidoh/esp8266_milight_hub#322]
I'm using a NRF24L01+PA+LNA with the Nodemcu v3. This is a NRF24L01 with added power amplifier (PA) circuit and Low Noise Amplifier (LNA) circuit. Is this a viable solution? Cause it does not work. 

After flashing I can get into the webinterface without problem but nothing happens when sniffing commands from an Ibox1. I checked https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting. I think my modules are ok (though The NRF24L01+PA+LNA was quite cheap (2 US$ directly from China)).

To provide further information, I flashed the precompiled binaries for Nodemcu v2. Couldn't get Platformio to work, as I didn't know where to put the commands:

    export ESP_BOARD=nodemcuv2
    platformio run -e $ESP_BOARD --target upload

(Maybe the guide can offer some more help for people who are new to this?)

**Comment by sidoh** [comment]
Knockoff NRF modules are highly problematic in my experience.  If you're getting $2 ones from ebay you're probably buying knockoffs. 

That's fine, I use them too, but keep in mind they have a pretty high DoA rate.  I would suggest buying 10 of them.

My understanding is that the PA+LNA module is a power hog.  Make sure you're using a great power supply.  Probably at least 500 mA.  Some folks have said a capacitor across Vin and Gnd on the NRF is necessary.

There's nothing wrong with using the pre-compiled binaries.  The commands would go in a terminal.  I'm more than happy to accept any PR that improves documentation.

**Comment by sidoh** [comment]
Going to close because it doesn't seem like a firmware issue.  Please feel free to reopen if that's not the case.

**Comment by Streep** [comment]
Thanks for your explanation. I think I made some error after all cause now it all works. Still trying to see what is a good power supply. Is there some way to test how much power it uses compared to one without PA+LNA? Maybe just wiring a multimeter between 3V of the MCU and the ESP?

I will see if I can add some lines and make a PR for PlatformIO once I figure it out myself.

**Comment by sidoh** [comment]
I don't know of a way that's better than using an ammeter/multimeter.

Oops, haha.  Well, feel free to open a new issue referencing this one.

**Comment by Streep** [comment]
Okay, will try that some time and report back here! First need to get OpenHAB working with this.

**Comment by rawframe** [comment]
Hi Streep, Did you ever get the NRF24L01+PA+LNA to work? If so how? M
