### ISSUE TITLE
Control bulbs using Domoticz

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#323]
i have add all controllers (remote ID) into the WebUI as gateway. Add them into domoticz.

I see that the RGBW Bulbs working correct Color, sat, bright. But RGBWW change from color to Kelvin there is a little problem.

When change from Kelvin to a Color that is working. When you want select Kelvin again, it show the kelvin level with bulb but then it switch directly to the last selected color.

**Comment by sidoh** [comment]
What remote type are you using?

Can you try disabling Automatic Mode Switching under Settings > Radio?

![image](https://user-images.githubusercontent.com/589893/44896919-b245b580-acae-11e8-839c-aa055ad15081.png)

**Comment by sidoh** [comment]
sweet 👍
