### ISSUE TITLE
Give Device ID a name

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#326]
Not a issue, but a request:

I love the Milight Gateway Emulator for ESP 8266. Test it now with 32 bulbs and work great. Maybe a idea to make the WebUI better? Give Device ID a Name. So i add "0xAAAA" and want give this the name "Livingroom" When you press the pull down you get a nice list of all Device ID's with a nice name: Livingroom, Bedroom, Kitchen.. etc you name it.

Keep up the good work!!!

**Comment by sidoh** [comment]
It's a good idea.

I think this is a duplicate of #210.  Does it look that way to you as well?

**Comment by sidoh** [comment]
Thanks, gonna close as a duplicate.  Appreciate the suggestion.

**Comment by poudenes** [comment]
Will this feature request be implemented in near future?

**Comment by sidoh** [comment]
I have no active plans to do so.  As you can imagine, I work on this project in my spare time.  So new features get added when both time and interest permit. :)

More than happy to look at a PR!

**Comment by poudenes** [comment]
We all more then happy you spend some of your time into this project!!
It was only a question :)

**Comment by sidoh** [comment]
Totally fair question, I didn't mind :)
