### ISSUE TITLE
unable to control the milight bulb

### ISSUE THREAD

**Issue by titusece** [sidoh/esp8266_milight_hub#342]
Hi,
I have two set of NRF + Nodemcu boards to control my milight bulbs.
I bought this nRF devices and NoduMCU devices. Hope this nRF device would be stable one and Nodemcu too.
http://www.elecfreaks.com/wiki/index.php?title=2.4G_Wireless_nRF24L01p_with_PA_and_LNA
Not able to control my milight bulbs using these two set of boards but remote control of milight.
Able to find the ID using sniffing and configuration seems okay.
Enabled sniffing on one board and another board sending the data, nothing received in sniffing output,and did vice versa.
So I suspect that board is not at all transmitting the data to milight, if so what could be problem.
Any suggestions or pointers to debug this issue. I need some stable setup and it should work all the time, so whats your suggestion here.,
Can you please help me on this.
Thanks.

**Comment by sidoh** [comment]
Hi @titusece,

this is a common issue.  Please take a look at the [troubleshooting guide](https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting) and open a new issue with the info requested at the bottom of the article if you're still having trouble.
