### ISSUE TITLE
Hub stop responding when overloaded with RESP API requests

### ISSUE THREAD

**Issue by cooltom** [sidoh/esp8266_milight_hub#343]
Hi playing with DiyHue hub which is talking to ESPmilightHub over REST API. Trying with Original Philips Hue app and other music sync and moods apps like Hue Disco, Hue Manic.
It works but problem is, that after little while the ESPbridge get overloaded and stop responding (even for ping).
I played with RF setting, but not much different. Any experience with this? What part of ESPMilightHug get overloaded with REST API requests. Any HW improovement possible? Maybe add module with LAN wire port?
Its not just about delay but about killing the Bridge with lot of requests …

**Comment by sidoh** [comment]
This is the best advice I have at the moment:

https://github.com/sidoh/esp8266_milight_hub/wiki/Performance-Tuning

You'll have better throughput (and latency) with MQTT because communication is happening over pre-established TCP connections, but don't count on much beyond 3-5 commands/s.

**Comment by poudenes** [comment]
I had same issue, changed some settings as well. Will post them later (at work now). After changing the settings all lag issues are gone. I use 1.8.1 Firmware. 1.8.2 and 1.8.3 gives me lot of lag problems.

**Comment by cooltom** [comment]
> 
> 
> I had same issue, changed some settings as well. Will post them later (at work now). After changing the settings all lag issues are gone. I use 1.8.1 Firmware. 1.8.2 and 1.8.3 gives me lot of lag problems.

Perfect, thanks a lot. Waiting for your setup.  With 1.8.1 and 1.8.3 I had problem save ID of virtual HUB. I type it into field click ADD but after refresh it doesnt remember. But i solve it with export setting, write new ID into json file and import it back :-)

**Comment by poudenes** [comment]
@cooltom  here my Radio settings:

Packet repeats = 25
Radio interface type = nRF24
Packet repeat throttle threshold = 1000
Packet repeat throttle sensitivity = 0
Packet repeat minimum = 5

**Comment by poudenes** [comment]
@cooltom did it work with the settings i post?

**Comment by cooltom** [comment]
> 
> 
> @cooltom did it work with the settings i post?

Hi, sorry for pate reply and thanks for sending values. I was moving OpenHab to esp8266 binding
Actually doesnt work for me. Can not see any different from prev setup :(

**Comment by cooltom** [comment]
> 
> 
> @cooltom here my Radio settings:
> 
> Packet repeats = 25
> Radio interface type = nRF24
> Packet repeat throttle threshold = 1000
> Packet repeat throttle sensitivity = 0
> Packet repeat minimum = 5

Actually it is bit better. I will also try overclock. Thank you again.

**Comment by cooltom** [comment]
> 
> 
> I think that there are multiple reasons for Hue being faster, at least these are obvious:
> 
>     * connection: ethernet (Hue) vs. wifi (MiLight); this isn’t even a fight as the throughput of the connection is not a factor in the smart devices world (a 100mbps ethernet link will destroy even a 1700mbps 4x4 AC wifi as the latency is the most important factor in terms of bridge response);
> 
>     * processor: MIPS 24Kc clocked at 650 Mhz (Hue - at least for v2 of the bridge) vs. 80 Mhz (ESP8266);
> 
>     * wireless protocol optimization: Zigbee, relatively well established although not yet de facto standard (Hue) vs. not regulated protocol (MiLight).
> 
> 
> Anyway, it’s not that much of a price difference between Hue and MiLight if willing to go with DIY and especially with led bands instead of bulbs. See the controllers mentioned below (one MiLight, one Hue compatible) which, combined with a good RGB+CCT/RGBWW/RGB/CCT led band, would get to a much lower price than an original Hue led band. I’ve tested both of them with a RGB+CCT led band and the results are great:
> 
>     * FUT045 controller has (literally) 0 connectivity issues or dropped packages during a 3 months timespan; in terms of reliability this is the best MiLight hardware I use (FUT105 comes second, but this is a light bulb);
> 
>     * Gledopto controller has similar response times compared to native Hue bulbs (I don’t have a native Hue led controller to compare with); haven’t checked with Hue Sync pc app, though; however, I expect to have same performances.
> 
> 
> As the led controllers give quite good results, in terms of hubs, Hue is in a class of its own.
> 
> In order to be able to get MiLight hardware working with home automation software, Chris’s emulator is the way to go, at least comparing with the ibox.
> 
> MiLight:
> https://s.click.aliexpress.com/e/c1ynx6sY
> 
> Hue compatible:
> https://s.click.aliexpress.com/e/bc769zcG

Ajaj seems like I choose wrong brand (Milight) :))))) GLEDOPTO looks good connect direct to Hue Bridge (one step on way to controlling app removed) but doble price for bulbs ...

Any plans use more powerful ESP with eth port? :)

**Comment by sidoh** [comment]
Sorta seems like we came to a resolution on this, except the general sentiment that throughput kinda sucks.  So gonna close this issue.  Feel free to comment if that's wrong and I can reopen.

There's another ticket for the Ethernet build (#215), but given my best understanding, it's a pretty huge undertaking, and not one that's likely to happen any time soon given the variety of other large items on the backlog.  But obviously I'm happy to collaborate on a PR. :)
