### ISSUE TITLE
Can not access milight-hub.local

### ISSUE THREAD

**Issue by Kralg** [sidoh/esp8266_milight_hub#344]
Hello,

I am trying to try te milight-hub. I have a ESP8266MOD (ESP-12f) and I connected to it the nrf24l01.
I also flashed the ESP with the ESP8266 download tool with the binary which ends with esp_12-1.8.3.bin.
I am attaching the picture of the program with the settings.
I can see that there is a new AP of the ESP which is called ESP_DA3C61, but when I connect to it it does not ask any password neither on Windows nor on Linux (raspbian).
When I connect to this AP I also can not access the http://milight-hub.local (I have bonjour server on Windows and Avahi on Linux).
Can you elaborate on what can be wrong here? 

On Linux with netstat -tuln I can not see any server listening on port 8080.

![programming_esp](https://user-images.githubusercontent.com/26962388/46061063-f4f39400-c16d-11e8-8f2c-353ee7616ea9.png)

**Comment by sidoh** [comment]
I'm not sure what to make of this.  The config AP should require a password.  If it doesn't, then I would say that either:

1. Flashing firmware didn't work (i.e., there's something else running on it)
2. The AP is coming from another device

possible i'm wrong, but don't have other ideas.

Things to try:

* Make sure you're selecting 32Mbit flash size (esp-12s have 4MB flash)
* Format before flashing

**Comment by Kralg** [comment]
Thank you there were few things which are not very complicated though. 
The check mark has to be selected near the .bin file which is needed to be flashed and the address should be set to 0x0000. 
Thank you.
