### ISSUE TITLE
MQTT json - Night mode

### ISSUE THREAD

**Issue by starkillerOG** [sidoh/esp8266_milight_hub#345]
I cannot seem to find the right command to set the bulbs into night mode with the MQTT JSON interface.
I am trying to get night_mode working with HomeAssistant.
Running version 1.6.4.

I did mange to find the white mode command:
`mosquitto_pub -h 192.168.1.??? -p ???? -u ??? -P ??? -t milight_control/0x????/fut089/0 -m {"effect":"white"}`
works for me and turns the bulb into white mode.
I would expect something like "night", "night_mode" to work, but it does not for me.

Could someone tell me the right syntax for night mode?
Is their also a syntax for setting the other modes like 0,1,2 etc?
Could the MQTT JSON API be added to the documentation?

**Comment by amelchio** [comment]
See here for Home Assistant configuration: https://github.com/sidoh/esp8266_milight_hub/issues/319#issuecomment-418900096
