### ISSUE TITLE
Interesting project, which support all MiLight protocols

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#35]
https://github.com/mwittig/node-milight-promise

**Comment by sidoh** [comment]
Right, I've seen this. I'm pretty sure this is purely a UDP client library, right? It doesn't do anything for the RF protocols.

**Comment by Lstt2005** [comment]
Yes, as i understand.

**Comment by sidoh** [comment]
Okay, cool. This is a good reference. Now that I can point the app at the ESP, though, it's pretty easy to reverse the protocol. Before I had to use some packet sniffing app on my phone, which was a colossal pain :)

**Comment by Lstt2005** [comment]
:) You work it's BIG WORK!
