### ISSUE TITLE
MQTT state after nightmode command

### ISSUE THREAD

**Issue by hencou** [sidoh/esp8266_milight_hub#358]
Hi,

MQTT returns state=ON after a night_mode command.
Shouldn't it be state=OFF? Now, after a night_mode command, I have to swith off the lamp first in HomeAssistant before I can turn it on again.

**Comment by sidoh** [comment]
Hmm... could probably go either way on this one.  Night mode seems more like an "on" state to me than an "off" state.

**Comment by hencou** [comment]
Hi Sidoh,

Maybe I'm thinking in the wrong way in HomeAssistant?
I've created 2 components now to enable light and night mode now:
-A MQTT Switch:
  - platform: mqtt
    name: "Woonkamer nachtmodus" 
    command_topic: "mesh_in/milight/0x1225/rgb_cct/1"
    payload_on: '{"command":"night_mode"}'
    payload_off: '{"status":"off"}'
-A MQTT Light:
  - platform: mqtt_json
    command_topic: "mesh_in/milight/0x1225/rgb_cct/1"
    state_topic: "mesh_out/milight/0x1225/rgb_cct/1"
    brightness: true
    color_temp: true
    name: Woonkamer tuindeuren
    rgb: true

I agree with you that's more a On state then Off, but I don't know how to solve that on a more elegant way in HA. How would you do this?

**Comment by sidoh** [comment]
I've seen some folks solve this with the `effect_list` feature of the mqtt_json component.

**Comment by sidoh** [comment]
Not sure if that gives you exactly what you want, though.

**Comment by amelchio** [comment]
Yes, using a night effect works fine for me.

For Home Assistant specifically, I also find it useful to enable [assumed state](https://www.home-assistant.io/docs/configuration/customizing-devices/#assumed_state). This gives separate on/off buttons like the MiLight remotes and not a toggle that can be wrong.

**Comment by hencou** [comment]
@Amelchio: how did you set up that night effect in Home Assistant?

**Comment by amelchio** [comment]
Like this: https://github.com/sidoh/esp8266_milight_hub/issues/319#issuecomment-418900096

**Comment by hencou** [comment]
Thats a better approach! Works perfect here now. Many thanks.

**Comment by sidoh** [comment]
Thanks @amelchio!

**Comment by hencou** [comment]
The effect "night_mode" is not working in version 1.9.0 anymore.
Adding "state.fields._isSetBulbMode = 1;" to the function setNightMode in \lib\MiLightState\GroupState.cpp seems to solve the problem:

_```
bool GroupState::setNightMode(bool nightMode) {
  if (isSetNightMode() && isNightMode() == nightMode) {
    return false;
  }

  setDirty();
  state.fields._isSetNightMode = 1;
  state.fields._isNightMode = nightMode;

  **state.fields._isSetBulbMode = 1;**

  return true;
}
```_

**Comment by sidoh** [comment]
Thanks, @hencou!  I've fixed this in #440.  Also added a test case to the integration test suite.

**Comment by servim** [comment]
Hi! Which version will fix it?
Now filled esp8266_milight_hub_d1_mini-1.9.0-rc.4.bin
On two versions of the lamps works differently.
1. RGBW with night mode turned ON
RGBCCT when switching on the night mode the general switch does not change.
2. RGBW Lamps OFF.
Press - white, the lamps will turn on in the mode in which they were before shutdown, but the on / off button will remain OFF

**Comment by sidoh** [comment]
1.9.0-rc.4 has the fix for the issue outlined by @hencou.

I believe the behavior you're describing has always been the case.  The RGBW packet formatter both turns on the bulbs and puts them into night mode.  The RGB+CCT does not -- it just sends the night mode command.

Not sure why, actually.  RGB+CCT bulbs will enter night mode regardless of whether they're off or on.  May not be the case with RGBW bulbs?

Other than the inconsistency being mildly confusing, does this cause you any trouble?

**Comment by servim** [comment]
> Other than the inconsistency being mildly confusing, does this cause you any trouble?

I do not know yet, I did not think that they could behave differently.
What say on the second question?


> 2\. RGBW Lamps OFF.
>     Press - white, the lamps will turn on in the mode in which they were before shutdown, but the on / off button will remain OFF, then you can change colors and modes, but the button shows that the lamps are OFF.

**Comment by sidoh** [comment]
Makes sense.  They might have to behave differently.  Milight's protocols are a bit of a mess. :)

Not entirely sure I'm following.  Are there some commands or screenshots you can share that reproduce the behavior?

**Comment by servim** [comment]
![ml](https://user-images.githubusercontent.com/22333446/56844168-98f91580-68de-11e9-879c-95cf52748949.png)
1 line: lamps on in color mode
2 line: pressed off, the lights went out
3 line: pressed white, the lamps turned on, but the button - off
4, 5 line: changed color, lamps changed color, but button - off
