### ISSUE TITLE
Add support RGBW + CCT FUT039 controller

### ISSUE THREAD

**Issue by mirkorobocop** [sidoh/esp8266_milight_hub#359]
Hello,

@sidoh Can you add support for FUT039? generally the controller works but it is not possible to choose white warm and cold white. Sometimes it shines cold sometimes warm

**Comment by sidoh** [comment]
Apologies for the late response, haven't had a lot of time to look at issues.

FUT039 should be supported.  Try pairing using the RGB+CCT or FUT089 protocols, which have support for choosing color temperature.

Feel free to open a new issue if you encounter issues.
