### ISSUE TITLE
Hassio dont accept mqtt_json after 2 latest update

### ISSUE THREAD

**Issue by darkice555** [sidoh/esp8266_milight_hub#362]
Hi Sidoh
After updating Hassio my MiLight stoped working.. It says "Unable to find component light.mqtt_json" and im using Mosquitto broker, it seems that Mosquitto finds the esp, but only my tasmota switches shows in hassio, sorry if their is solutions on the page, but im a noob in this world.. heres my config to Hassio:  
mqtt:

  broker: core-mosquitto
light:
  - name: "Livingroom"
    command_topic: milight/0x1/rgb_cct/1
    state_topic: milight/states/0x1/rgb_cct/1

    <<: &MILIGHT_PARAMS
      platform: mqtt_json
      color_temp: true
      rgb: true
      brightness: true
      effect: true
      effect_list:
        - white_mode
        - night_mode
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8

  - name: "Fireplace"
    command_topic: milight/0x2/rgb_cct/1
    state_topic: milight/states/0x2/rgb_cct/1

    <<: *MILIGHT_PARAMS

**Comment by sidoh** [comment]
Yeah, they refactored some stuff.  I don't quite understand why they don't roll out these kinds of changes more gracefully.

See #361.  The documentation has been updated.

**Comment by sidoh** [comment]
The concrete fix is to change this:

```yaml
<<: &MILIGHT_PARAMS
platform: mqtt_json
```

to this:

```yaml
<<: &MILIGHT_PARAMS
platform: mqtt
schema: json
```
