### ISSUE TITLE
Feature Request: Save Device Id together with Remote Type

### ISSUE THREAD

**Issue by matrix1000** [sidoh/esp8266_milight_hub#370]
Hi,

In my eyes, an ID can only have one type of remote type (RGBW, CCT...). 
Am I getting this right?

It would therefore be a dream if the ID were stored together with the remote type.

So that when I select an ID, the correct remote type is selected too.

Many thanks.

**Comment by sidoh** [comment]
An ID can have any remote type, actually.  Remote type is essentially "protocol version," and the same ID can be reused for all of them.

**Comment by matrix1000** [comment]
Ok, so if it doesn't make sense, you can close this case. :-) Thank you for your time.
