### ISSUE TITLE
Device Identification/Support Needed: Possibly FUT005 no sniffing or data available

### ISSUE THREAD

**Issue by caffeineflo** [sidoh/esp8266_milight_hub#377]
Hey,

I know this is not the support forum, yet, I couldn't find a better place and was hoping someone could help me figure this out so eventually I could bring back support for my issue to this project in a future PR.

I bought a lamp like the pic below a while back and figured given that the remote is 2.4GHz and the controller looks similar to some MiLight controllers that it might be milight and I could use this project to control my lamp. 
![htb1irxjwhrpk1rjszteq6awavxar](https://user-images.githubusercontent.com/1525283/51392476-21f3fa00-1b03-11e9-991d-25b64d921833.jpg)
As it seems now, it's not quite milight. While the controller and remote responds to the same pairing/unpairing procedures, I can't sniff any data or pair it with my milight hub.

Initially I thought it might be my NRF24l01 chip or some wiring, but after testing 5 different NRF24l01 chips and several ESP's I'm certain it's not that.

Here are images of the controller and remote circuits. Initially I was thinking it's the FUT005 remote, but I'm uncertain about that now that it's not working.
![img_9298](https://user-images.githubusercontent.com/1525283/51393173-14d80a80-1b05-11e9-9a11-4385739bfcf5.jpg)
![img_4301](https://user-images.githubusercontent.com/1525283/51393174-14d80a80-1b05-11e9-9aff-d99fb94cdad5.jpg)
![img_4672](https://user-images.githubusercontent.com/1525283/51393175-1570a100-1b05-11e9-905d-6c5ad3679ded.jpg)
![img_3540](https://user-images.githubusercontent.com/1525283/51393176-1570a100-1b05-11e9-8f6f-14dec56868e0.jpg)
The lamp only does color temperature, white only and night mode.

If anyone could lead me in the right direction and/or help identify what I have here, that would be great! 

Thanks

**Comment by sidoh** [comment]
I'm not sure this is a milight device.  Was it branded as such from the place you bought it?

Hard to tell without taking a closer look at the board on the remote.

**Comment by caffeineflo** [comment]
@sidoh The picture of the blue PCB is the remote.

Reason why I believe it's a MiLight is that the exact same pairing and unpairing procedures work.

Any clue how I could further investigate?

**Comment by sidoh** [comment]
What does the other end look like?  I'd recommend trying:

1. Check serial logs with DEBUG_PRINTF enabled
2. Sniff the SPI bus on the remote

**Comment by caffeineflo** [comment]
Here are some more pictures or the remote. I'll crack out the buspirate and see if I can sniff anything on the SPI bus

![img_2253](https://user-images.githubusercontent.com/1525283/51496292-35b29100-1d8d-11e9-9e00-5e68b1225763.jpg)
![img_0876](https://user-images.githubusercontent.com/1525283/51496293-35b29100-1d8d-11e9-86a6-ca8a9cfece29.jpg)
![img_5747](https://user-images.githubusercontent.com/1525283/51496294-35b29100-1d8d-11e9-887a-7ed58c1972cb.jpg)

**Comment by sidoh** [comment]
I'm not sure this is a milight device.  Milight devices typically have a separate microcontroller and 2.4 GHz radio (LT8900).  That doesn't seem to be the case here.

Going to close for now, please let me know if you'd like to reopen.  I'd need a device to test with or SPI dumps to get much further.

**Comment by caffeineflo** [comment]
As expected I haven't had time to do a SPI dump. Now I have both a logic analyzer and a bus pirate next to me, but where and how would you apply the logic analyzer to get an SPI dump as I can't identify the IC1 that would be the only thing I can think of here?!

**Comment by sidoh** [comment]
Given there isn't a separate RF module (I don't see one anyway), maybe there's no SPI to sniff.

**Comment by caffeineflo** [comment]
The remote is gone as of today. Seemed to had some error state and now I'm about to put in another receiver.

Thanks for your replies though!
