### ISSUE TITLE
Is it possible to reduce and raise the brightness without changing the other parameters through the MQTT

### ISSUE THREAD

**Issue by odis68** [sidoh/esp8266_milight_hub#381]
Is it possible to reduce and raise the brightness without changing the other parameters through the MQTT. (GET command level_down, level_up)
Thank you for your work !!!

**Comment by sidoh** [comment]
yes, you can set the brightness directly.  MQTT supports the same parameters the REST API does.

https://github.com/sidoh/esp8266_milight_hub#bulb-commands

**Comment by sidoh** [comment]
Please let me know if this doesn't answer your question.
