### ISSUE TITLE
[FR] MilightHub behind Path-Routing Proxy

### ISSUE THREAD

**Issue by DerOetzi** [sidoh/esp8266_milight_hub#389]
Hi,

I'm building up a Proxy-Server to enable access to my smarthome devices, which have an web-ui.
The proxy is determinating the correct device with the given Path like this:

https://proxyurl.com/device1
https://proxyurl.com/device2

For this devices have to use relative path for linking and resources.

The milight hub is loading well, but the websocket connection is established not to the "base url" path but to the host root. Would it be possible to change this behaviour?

**Comment by sidoh** [comment]
The websocket library being used is decoupled from the HTTP server, and runs on a different port (81).  No way for them to run on the same port, if that's what you're asking.

**Comment by DerOetzi** [comment]
No that is okay, but you're using only location.hostname:81 to open. What I would need is hostname:81/current_subpath/

**Comment by sidoh** [comment]
Hi @DerOetzi, were you able to get what you needed?

**Comment by sidoh** [comment]
Gonna close since I haven't heard back, but please feel free to bump the ticket.
