### ISSUE TITLE
Support for FUT025 or FUT027 planned?

### ISSUE THREAD

**Issue by SHEVienna** [sidoh/esp8266_milight_hub#394]
Is the support for FUT025 or FUT027 planned?

![img_0316](https://user-images.githubusercontent.com/35074850/52492263-1c9d4300-2bc9-11e9-9741-8bc6d1ed1668.JPG)

**Comment by sidoh** [comment]
Looks pretty similar to FUT098, which is already supported.

https://github.com/sidoh/esp8266_milight_hub/issues/21

Have you tried it?

**Comment by SHEVienna** [comment]
Thx - works with pairing.
