### ISSUE TITLE
One question - Milight app ver 3 work in last version?

### ISSUE THREAD

**Issue by itProfi** [sidoh/esp8266_milight_hub#397]
Hi for all! As i write on 30 on march 2017 - https://github.com/sidoh/esp8266_milight_hub/issues/27#issuecomment-290818506 milight app works...
But today version 1.9 - not found any gateawy - what's i do wrong?

**Comment by wknutsen** [comment]
https://github.com/sidoh/esp8266_milight_hub/issues/128
Is related to this issue

**Comment by sidoh** [comment]
Going to close as a duplicate
