### ISSUE TITLE
Add button to control light 

### ISSUE THREAD

**Issue by Mslawkowski** [sidoh/esp8266_milight_hub#400]
I have an idea. next time you update, you can add options so that you can use gpio to connect a programmable button. it's possible to use the bell button instead of the ugly touch panel.

What do you think? 
written with a translator

**Comment by sidoh** [comment]
Hi @Mslawkowski,

This one slipped through the cracks, I apologize.

It's a nice idea, although I'm a bit wary of adding too many features like this.  The software is already way more bloated than I expected it to be.

If many people want it, I'm happy to look into it.  But might be best off implementing it in a fork.

**Comment by sidoh** [comment]
Gonna close this, but happy to discuss further if you'd like.

**Comment by feder-ico** [comment]
Hi,
What if I want to ad a button to turn a digital pin on Hight or Low?

Should I include the button on index.html, but what else should I do to finally execute `digitalWrite(13, HIGH);` for example?

Any hint woul be appreciated!

Thanks in advance.
