### ISSUE TITLE
china RGB milight clones

### ISSUE THREAD

**Issue by coolduke666** [sidoh/esp8266_milight_hub#408]
hi

does anybody knows if the cheap china milight clones for RGB led stripes (controller plus remote approx 7 USD) works with this hub? or are the using another proprietary protocol which is different? 

remote looks like FUT098 ;) 

thx

**Comment by sidoh** [comment]
I personally have no idea :)

**Comment by coolduke666** [comment]
to all: china clones are using a non compatible protocol and therefore are NOT usable with the milight hub :(

**Comment by sidoh** [comment]
Thanks @coolduke666.  Happy to dig into this a little more if you have more information.

**Comment by afska** [comment]
any news on support for this controller?

@coolduke666 does your rgb controller look like this?

![image](https://github.com/sidoh/esp8266_milight_hub/assets/1631752/e85db0b3-3287-4d76-b260-c528399a114d)
