### ISSUE TITLE
Add FUT037 Controller without remote? 

### ISSUE THREAD

**Issue by coolduke666** [sidoh/esp8266_milight_hub#412]
hi

is it possible to add a controller eg FUT037 for RGB without a remote? then you can't sniff any packages... 

because I don't need a milight controller when using MQTT :) 

how to configure the hub then? 

thx

**Comment by garmck** [comment]
Have you read the wiki?
Its detailed there [https://github.com/sidoh/esp8266_milight_hub/wiki/Pairing-new-bulbs](https://github.com/sidoh/esp8266_milight_hub/wiki/Pairing-new-bulbs)

**Comment by coolduke666** [comment]
sure but I dont want to pair a bulb... I want to pair a LED strip
controller.

garmck <notifications@github.com> schrieb am So., 10. März 2019, 23:39:

**Comment by coolduke666** [comment]
I dont want to pair a bulb... I want to pair a LED strip controller.

**Comment by sidoh** [comment]
It's the same process.

**Comment by sidoh** [comment]
Gonna close, @coolduke666.  Happy to answer further questions if you've got 'em.
