### ISSUE TITLE
After wifi restart lag problems 

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#432]
Hi all,

When wifi is reboot (for a reason) and u don't restart the hub then I get lots of lag problems. After reboot the hub and then domoticz all problems are gone.

Question : is it possible to give the hub a reboot command from a http line?

I want do a restart of domoticz, first restart hub then wait 5 sec and then Restart domoticz...

Greets
Peter

**Comment by sidoh** [comment]
Huh, weird.  Shouldn't be the case.  Would be curious to see Serial logs after a wifi reboot.

Anyway, yes, it's possible.  Check out the [REST API documentation](https://github.com/sidoh/esp8266_milight_hub#rest-endpoints).  Example curl command:

```
$ curl -X POST -H 'Content-Type: application/json' -d '{"command":"restart"}' http://milight-hub/system
```

**Comment by poudenes** [comment]
Thanks,  

Serial log is not easy. Module is build in somewhere so can't take it out easily :)

**Comment by sidoh** [comment]
Cool.  Let me know if that changes.  Will close for now. :)
