### ISSUE TITLE
Ha Bridge Example

### ISSUE THREAD

**Issue by dougdalton** [sidoh/esp8266_milight_hub#439]
Does someone have an example of how to do a ha bridge http json request that works with basic authorization required by the milight hub? I have used off as my example below

I have done an a http request with the target item : 
http://username:password@192.168.2.100/gateways/0x5685/rgbw/1

with http verb put and the http headers: 
[{"status": "off"}]
 
Content type : application/json

but I get a spark.matching error, what its the correct way to do this?

**Comment by sidoh** [comment]
> http headers:
> [{"status": "off"}]

Not sure if this is what you meant, but these shouldn't be headers.  It should be the body of the request.

See examples here:

https://github.com/sidoh/esp8266_milight_hub#examples

**Comment by dougdalton** [comment]
that was the issue,  thank you
