### ISSUE TITLE
Compatibility with Mi-Light clone

### ISSUE THREAD

**Issue by cristianlivella** [sidoh/esp8266_milight_hub#446]
Hi. I tried to buy a Mi-Light iBox2 to control my RGB stripes via WiFi, but I can't pair it with my RGB controllers. So I checked better, and I noticed that my controllers and remotes are apparently like Mi-Light FUT025/FUT098, but there aren't "Mi-Light" logos on them, so I think they are clones, and they don't work with iBox2. You think that I could use ESP8266+NRF24L01 to control my RGB stripes? Thanks

**Comment by sidoh** [comment]
Would imagine it's possible in theory.  Probably not something this project in particular can help with, though. :)

**Comment by sidoh** [comment]
Gonna close this because I think it's out of scope.  But happy to discuss further if you'd like.
