### ISSUE TITLE
iLightShow or Hue Sync

### ISSUE THREAD

**Issue by dougdalton** [sidoh/esp8266_milight_hub#450]
Has anyone used your emulator with a music to light syncing app?

**Comment by sidoh** [comment]
#107 seems relevant, but not sure if that's what you have in mind.

I will probably not incorporate anything like this natively, but the integrations/APIs should allow you to set something like this up with some glue components.

**Comment by sidoh** [comment]
Going to close the issue since I haven't heard back.  Feel free to continue the discussion, though.
