### ISSUE TITLE
How do I 'ping' a lightbulb to see if it's alive

### ISSUE THREAD

**Issue by robdejonge** [sidoh/esp8266_milight_hub#453]
The commands and updates I see over MQTT originate from the hub, rather than the actual light bulbs. I don't see any way to figure out conclusively, if a bulb is 'online' or not. How could I achieve this?

**Comment by garmck** [comment]
The bulbs are passive. They have no transmitters. 
If you need status, you are best using a WiFi type bulb.

**Comment by robdejonge** [comment]
That settles that then. 😄
Thanks!

**Comment by robdejonge** [comment]
Sorry to abuse this forum for product questions, but I was just wondering if the same applies to the LED strip controllers - do they too not have transmitters?

**Comment by sidoh** [comment]
Yes, as far as I know they're one way as well.
