### ISSUE TITLE
Wiki update (Not issue related)

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#478]
in Wiki you can remove the line:
Note: Remember the Group All is not working yet. They still develop this part

Add both for Hub and Plugin:
MQTT update Pattern: milight/updates/:hex_device_id/:device_type/:group_id

**Comment by sidoh** [comment]
will update, thanks.

are MQTT updates needed for the plugin to function?

**Comment by sidoh** [comment]
done

**Comment by poudenes** [comment]
Yes. The plugin is based on MQTT ... it work Perfect !!! Im so happy. reaction time is so much faster now then before... 

The MQTT update pattern is extra for the update group_all. It work like a charm !!!

**Comment by sidoh** [comment]
sweet. thanks for helping maintain the docs!

**Comment by poudenes** [comment]
> done

Thanks will close this now :)
