### ISSUE TITLE
MQTT command for RGB_CCT 

### ISSUE THREAD

**Issue by Tanto4** [sidoh/esp8266_milight_hub#486]
When a MQTT command is sent for a RGB_CCT light, the update reply is sent from a CCT light.

`milight/command/0x1/rgb_cct/1`
Reply is from:
`milight/update/0x1/cct/1`

This is in version 1.10.0 dev5

**Comment by sidoh** [comment]
Thanks for reporting.  Bug was introduced in this commit:

https://github.com/sidoh/esp8266_milight_hub/commit/17eb0fd57c7f9bb4b7c607505e29c6d4c432d604

Sadly tests caught this, but I hadn't run them.

**Comment by sidoh** [comment]
Will be fixed in 1.10.0-dev.6.

**Comment by Tanto4** [comment]
Thanks for the fast reply and fix!
