### ISSUE TITLE
Feature request: Add hostname to title + header

### ISSUE THREAD

**Issue by stefanheijnen** [sidoh/esp8266_milight_hub#489]
It would be nice to identify in an instance which hub I'm working. Especially when you have multiple hubs. Now I have to peek at my settings from time to time.

![image](https://user-images.githubusercontent.com/1306331/61576837-2a8fb200-aadf-11e9-9a0d-28b7f7727c5e.png)

**Comment by sidoh** [comment]
Sure, good idea.  Only solvable after page load w/ javascript, though.  Assets served are static.

**Comment by sidoh** [comment]
Live in 1.10.0-dev.7.

**Comment by poudenes** [comment]
NIce!

**Comment by stefanheijnen** [comment]
You're the best!
