### ISSUE TITLE
Added support for HEX color support in payload?

### ISSUE THREAD

**Issue by MrSiO** [sidoh/esp8266_milight_hub#499]
Is there a way (or consider as a feature request) to use the hex color values (#FFFFFF) in the MQTT color payload instead of RGB?

Many MQTT dashboards use HEX natively.

Thx for considering.

**Comment by sidoh** [comment]
Seems fine, although I think it'd have to be prefixed with the `#`.  It already supports a string in the form of `r,g,b`, and parsing would be a bit gross without the prefix.  

Would you need it to be two-way?  It's pretty easy to make it write-only, and a bit harder to make it read/write.  Write-only means you can send commands in this format, but state updates sent by the hub cannot be.

**Comment by MrSiO** [comment]
Write only would be a great.
I did a test and yes the # is included in the payload:

Eg:
#db8921

Thx for considering!

**Comment by sidoh** [comment]
Will be in the next 1.10 release.  Added a field as well so it's read/write.

**Comment by MrSiO** [comment]
Excellent! Thx alot!
