### ISSUE TITLE
new MQTT pattern token suggestion

### ISSUE THREAD

**Issue by csigabit** [sidoh/esp8266_milight_hub#504]
Hi!
Is there a way to use the device names instead of device_id in the mqtt pattern?
It would be much nicer that way and dealing with the remote control codes will become much easier.
Thank You for the answer and this awesome project!
Bests

**Comment by sidoh** [comment]
Hiya.

This is already available in the 1.10 release, which is in release candidate stages right now.  See the [README for documentation](https://github.com/sidoh/esp8266_milight_hub/tree/v1.10.0-wip#more-detail-on-mqtt_topic_pattern).
