### ISSUE TITLE
Sniffing MiBox 2 (v6) doesn't work

### ISSUE THREAD

**Issue by Catskan** [sidoh/esp8266_milight_hub#517]
Hello guys,

I'had set up my new NodeMCUv3 card with the latest version of your firmware and it's ok.

I connect to the web interface and I'm trying to sniffing my official MiBox 2 (v6).

I active the sniffing option, but when I use the MiApp (Android) to switch color or other option, nothing display on the webui under the part.
![image](https://user-images.githubusercontent.com/17289964/64350832-954a6d80-cff9-11e9-810b-6db46bd881b1.png)

I had tried to disconnect/reconnect my NoceMCU3 and the MiBox 2 but doesn't work.

I haven't physical remote, I use only my smartphone (Mi 9).

There are other options to sniffing my MiBox ?

Thanks you in advance for your help !

King Regards,

Sorry for my english

**Comment by sidoh** [comment]
I have one of these too, and I see traffic from it.

Please check out the [troubleshooting guide](https://github.com/sidoh/esp8266_milight_hub/wiki/Troubleshooting).
