### ISSUE TITLE
how can i run this on mac os?

### ISSUE THREAD

**Issue by janczakb** [sidoh/esp8266_milight_hub#521]
How can i run this on mac os? 
Could you give me a brief installation guide?

**Comment by sidoh** [comment]
Run what?  The build?

**Comment by janczakb** [comment]
@sidoh Yes, I would like to run the script and be able to go to http://milight-hub.local

**Comment by sidoh** [comment]
There's pretty extensive documentation in the README.  Please follow that.

**Comment by sidoh** [comment]
@janczakb, if what you're asking is how to run the actual software on OS X, the answer is you can't.

Otherwise, the relevant docs are here -- https://github.com/sidoh/esp8266_milight_hub#installing

please let me know if you have specific questions.
