### ISSUE TITLE
mDNS on Android

### ISSUE THREAD

**Issue by feder-ico** [sidoh/esp8266_milight_hub#528]
Is there any way to access the UI with Chrome on Android without knowing the IP address?
I tried using http://milight-hub.local but doesn't work.

**Comment by sidoh** [comment]
I don't think Android supports mDNS natively.  You'd probably have to find some application for it.

The way I accomplish this on my home network is by setting a hostname.  My router's DNS is configured to resolve internal hostnames.  If ti helps, the default hostname is `milight-hub`.

**Comment by sidoh** [comment]
Going to close since there's not a ton I can do here, but let me know if I've missed something.
