### ISSUE TITLE
Support multiple commands in the same request

### ISSUE THREAD

**Issue by sidoh** [sidoh/esp8266_milight_hub#55]
Sending a single command should still work. Should be possible to run the same command more than once. Example:

```json
{"commands":["increase_brightness","increase_brightness"]}
```

**Comment by WoodsterDK** [comment]
Ahh.. makes sense that I couldn't find the implementation.... 
This solution could absolutely work.

**Comment by sidoh** [comment]
Haha, yeah. Just meant to suggest an approach :)

**Comment by WoodsterDK** [comment]
It could work.... :+1:

**Comment by sidoh** [comment]
Oh, I think this is done in 1.2.0 btw. Forgot to put it in the release notes.
