### ISSUE TITLE
Is there an easier way?

### ISSUE THREAD

**Issue by agoralive** [sidoh/esp8266_milight_hub#550]
![image](https://user-images.githubusercontent.com/10817998/68088396-1dfd5280-fe5f-11e9-8d3d-d0d24e880d02.png)

What I do is:

1. Receive a message from MQTT server
2. Converts into json
3. Moves to msg.payload
4. Determine how many clicks the Xiaomi Button got
5. Reads the file that contains latest state
6. Directs the flow to the opposite direction of the file contents
7. Sets the payload to on or off
8.1. Sends the mqtt to ESP8266 Milight Hub
8.2. Prepares for change the state within the log file
9. Saves the latest state into the log file, and is it ready for next "push of a button"

I have multiple ESP8266 Milight Hub's running, the TOGGLE funtion will not work here :(.

I would like to keep it simple, so no database solutions please....

**Comment by sidoh** [comment]
What problem are you trying to solve?

**Comment by agoralive** [comment]
Trying to find a "simpler" solution for the flow above

**Comment by sidoh** [comment]
Right.  Can you please summarize what you're trying to accomplish with the flow?

**Comment by agoralive** [comment]
This flow allows a Xiaomi switch to control the milight bulbs using mqtt. 

Only the toggle function can not be used due to multiple milight hubs running.

**Comment by sidoh** [comment]
It seems like [context](https://nodered.org/docs/user-guide/context#context-scopes) is a pretty natural solution, no?  Not functionally different than reading from a file, just makes fewer assumptions about environment.

**Comment by sidoh** [comment]
Gonna close since my understanding is that this isn't really an issue with espMH.  Happy to discus further, though.
