### ISSUE TITLE
Transition POST operation issue

### ISSUE THREAD

**Issue by kgoik** [sidoh/esp8266_milight_hub#551]
Hi

I'm trying to use the transition endpoint to gradually change the brightness of my bulb. I've found a problem with either the code or docs:

In the docs there is a filed called device_type

{

    "field": "brightness",
    "start_value": 0,
    "end_value": 0,
    "duration": 0,
    "period": 0,
    "id": 0,
    "last_sent": 0,
    "bulb": 

    {
        "device_id": 1234,
        "group_id": 1,
        **"device_type"**: "rgb_cct"
    },
    "current_value": 0

}
Where the code is looking for following params:

void MiLightHttpServer::handleCreateTransition(RequestContext& request) {
  JsonObject body = request.getJsonBody().as<JsonObject>();

  if (! body.containsKey(**GroupStateFieldNames::DEVICE_ID**)
    || ! body.containsKey(**GroupStateFieldNames::GROUP_ID**)
    || ! body.containsKey(**F("remote_type"))**) {
    char buffer[200];
    sprintf_P(buffer, PSTR("Must specify required keys: device_id, group_id, remote_type"));

    request.response.setCode(400);
    request.response.json[F("error")] = buffer;
    return;
  }

I've tried to use different values both with device_type and remote_type but nothing works. I constantly receive error:

400 {'error': 'Must specify required keys: device_id, group_id, remote_type'}

### Steps to reproduce

invoke https://host/transitions POST method with 

[
  {
    "field": "brightness",
    "start_value": 0,
    "end_value": 100,
    "duration": 1,
    "period": 10,
    "id": 1,
    "last_sent": 0,
    "bulb": {
      "device_id": 6545,
      "group_id": 1,
      "remote_type": "REMOTE_TYPE_RGB_CCT"
    },
    "current_value": 0
  }
]

### Expected behavior

Transition is invoked properly.

#### Firmware version

1.10.3-6-g95bd7fc (nodemcuv2)

#### Output of http://milight-hub.local/about

```json
{"firmware":"milight-hub","version":"1.10.3-6-g95bd7fc","ip_address":"192.168.5.22","reset_reason":"Power on","variant":"nodemcuv2","free_heap":18296,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}
```

#### Output of http://milight-hub.local/settings

```json
{"admin_username":"","admin_password":"","ce_pin":4,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"","mqtt_username":"","mqtt_password":"","mqtt_topic_pattern":"","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"","mqtt_client_status_topic":"","simple_mqtt_client_status":false,"discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":0,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"On","led_mode_operating":"Slow blip","led_mode_packet":"Flicker","led_mode_packet_count":3,"hostname":"milight-hub","rf24_power_level":"MAX","rf24_listen_channel":"LOW","wifi_static_ip":"","wifi_static_ip_gateway":"","wifi_static_ip_netmask":"","packet_repeats_per_loop":10,"home_assistant_discovery_prefix":"","wifi_mode":"n","default_transition_period":500,"rf24_channels":["LOW","MID","HIGH"],"device_ids":[6545],"gateway_configs":[],"group_state_fields":["state","brightness","mode","color_temp","bulb_mode","computed_color"],"group_id_aliases":{"budzik":["rgb_cct",6545,1]}}
```

**Comment by sidoh** [comment]
Hello,

Oops, I thought I had fixed this, but apparently not.  I'll fix.

**Comment by sidoh** [comment]
Fixed in [1.10.5](https://github.com/sidoh/esp8266_milight_hub/releases/tag/1.10.5).

**Comment by sidoh** [comment]
(btw, the correct structure for `POST` is this):

```json
{
  "field": "brightness",
  "start_value": 0,
  "end_value": 255,
  "duration": 10,
  "device_id": 1234,
  "group_id": 1,
  "device_type": "rgb_cct"
}
```

Docs should reflect this now:

https://sidoh.github.io/esp8266_milight_hub/branches/1.10.5/

**Comment by sidoh** [comment]
Thanks for reporting!
