### ISSUE TITLE
multiple references in documentation to "Bulb commands" section - where is this ? 

### ISSUE THREAD

**Issue by s1nbad** [sidoh/esp8266_milight_hub#553]
#### /about

```json
"... /about output. put between the ```s"
```

#### /settings

```json
"... /settings output. put between the ```s"
```

**Comment by sidoh** [comment]
Same schema as the REST API.  Here:

https://sidoh.github.io/esp8266_milight_hub/branches/latest/#tag/Device-Control/paths/~1gateways~1{device-id}~1{remote-type}~1{group-id}/put
