### ISSUE TITLE
FUT089 hex color 

### ISSUE THREAD

**Issue by YorickJanse** [sidoh/esp8266_milight_hub#560]
Hi,

If the color is set for a FUT089 configured light the color will be hex in the state topic e.g.:

{"state":"ON","status":"ON","brightness":209,"level":82,"hue":344,"saturation":100,"color":"#FF0043","bulb_mode":"color"}

Home Assistant can not handle hex for color

If I uncheck hex in settings Group state fields, color will be null (light is set to a color):
{"state":"ON","status":"ON","brightness":209,"level":82,"hue":240,"saturation":86,"color":null,"bulb_mode":"color"}

When the light is set to no color the output is (setting Group state fields with or without hex enabled):
{"state":"ON","status":"ON","brightness":227,"level":89,"kelvin":100,"color_temp":370,"bulb_mode":"white","color":{"r":255,"g":255,"b":255},"effect":"white_mode"}"

For Home assistant the output should always be in the RGB format.

**Comment by sidoh** [comment]
Use `computed_color` for HomeAssistant.

https://github.com/sidoh/esp8266_milight_hub/wiki/HomeAssistant

> Make sure you've got the appropriate group_state_fields selected. The default values should work: state, brightness, computed_color, mode, color_temp, bulb_mode.
