### ISSUE TITLE
FUTC01 confirmed working

### ISSUE THREAD

**Issue by pauluzs** [sidoh/esp8266_milight_hub#568]
Didn't see it in the list yet.
Can confirm just successfully paired the FUTC01 
Used device id 123 and FUT089/B8 as remote type.

Greets Pauluzs

**Comment by sidoh** [comment]
Glad it's working for you.

I don't have a great exhaustive list.  Supported devices using FUT089 right now, for example, just reads:

> Most newer rgb + dual white bulbs and controllers

I'll keep this in mind if I ever build out a more explicit list, though.  Thank you!
