### ISSUE TITLE
Indicator in WebUi when new firmware is pushed

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#588]
Would be nice to have a indicator on webui thats show when a new firmware is pushed alive.
Maybe also this indicator can be send over MQTT "firmware":"true" or "false" so you can add this in your HA system. From there you can create some automations: notifications, send email. etc.

**Comment by sidoh** [comment]
Makes sense.  Pretty easy to do in the UI because the Github API is CORS-enabled (meaning it's just some frontend code).

Doing it through the backend is more heavyweight and probably not something I'd pursue.
