### ISSUE TITLE
Add groups in web interface

### ISSUE THREAD

**Issue by Bl00d-B0b** [sidoh/esp8266_milight_hub#595]
Hello,

Currently you have only 4 groups in web interface.
![image](https://user-images.githubusercontent.com/23188529/74150936-4d182280-4c0b-11ea-82fe-cb4ccc10b0ed.png)
But I have 8 and 256 group remote controls. Maybe it's possible to have settings, where you can specify amount of groups for each device ID.

Ed

**Comment by sidoh** [comment]
Hi, thanks for the suggestion.

FUT089 is supported and has 8 groups.  Select it in the remote type dropdown.

The 99 group remote is not supported right now (see #209).
