### ISSUE TITLE
everything running op a RPi3/4

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#602]
Hi,

Will it even possible to build software do you can run Milight Hub from an RPi3/4 ?
RPi3/4 have lots of pins and maybe more powerful ?

Cheers,

p.s.
here is a link how to do it with other software and tools:
https://magpi.raspberrypi.org/articles/pi-mi-light

**Comment by sidoh** [comment]
Hi @poudenes,

This has come up a few times (see #383, #58).  Out of scope for this project, but it's certainly possible.

Still a big project (but more within the realm of possibility) is adding support for ESP32, which is far beefier.
