### ISSUE TITLE
Feature request: Toggle back to night mode

### ISSUE THREAD

**Issue by csigabit** [sidoh/esp8266_milight_hub#604]
Hi,
I think the toggle command should switch back to night mode if the lamp was in night night mode when it was toggled off.
Bests!

**Comment by sidoh** [comment]
I'd like to keep the semantics of toggle very clear -- it toggles on/off. Night mode interplays with on/off in some sort of unexpected ways (for example, bulb doesn't respond to any commands except "off" or "on" when in night mode), so don't want to create any unexpected complications that arise from that.
