### ISSUE TITLE
Color carryover following change of bulb_mode

### ISSUE THREAD

**Issue by waparo** [sidoh/esp8266_milight_hub#610]
### Describe the bug
When controlling Fut086 (RGB-CCT) using milight hub (1.10.5) MQTT Explorer reports that the following commands were sent (last in time at the bottom)
{"status": "On", "brightness": 200, "bulb_mode": "white", "color_temp": 180}
{"status": "Off", "brightness": 0, "bulb_mode": "color"}
{"status": "On", "brightness": 2, "bulb_mode": "color", "color": {"r": 20, "g": 7, "b": 0}}

### Steps to reproduce
This is hopefully a problem of my understanding of the settings of the json command or a limitation of the milight logic.   I have a simple Python test program but it is running in an Appdaemon / Home Assistant environment. 

### Expected behavior
expected light to run the sequence - white, off, dull salmon color
but what happens is - white, off, white for a fraction of a second, dull salmon color-->
A bright white flash is not expected when I send a command to set light to a dull salmon colour.
#### Firmware version
1.10.5

### I am happy to try to set up a simpler reproducible package.  
The salmon color is used for sensor controlled night lighting and the initial flash of white light is a bit disconcerting at 2am!  I have searched for other similar experiences but have not found a solution. Thanks, Chris, for any help.

**Comment by sidoh** [comment]
Hi,

Can you paste your settings?

**Comment by waparo** [comment]
Chris, I seem to have made a complete mess of my post and would appreciate your deleting it.
I will start again with a new post.

**Comment by sidoh** [comment]
Oh, the HTML comments I had in the template are eating what you wrote.  I see it now, don't worry about creating a new post.

**Comment by sidoh** [comment]
I think probably what's going on here is that Milight bulbs maintain separate brightness levels for color and white modes.  So setting the brightness when the bulb is in white mode does not affect the brightness when you switch to color mode.

If you want to avoid being blinded when the light is turn back on, set the bulb to whatever mode you'll end up in.  You might be trying to do that with the `bulb_mode` attribute in the second command, but that attribute is read-only (this is confusing -- sorry).

I'd recommend changing your second command to something like this:

```json
{"status": "Off", "color":"20,7,0","brightness": 0}
```

That way the bulb will be very dim when it's first turn on in the 3rd command.

**Comment by waparo** [comment]
Chris, 
That has certainly stopped the annoying white flash.  But now I am seeing an annoying salmon flash as the white flash turns off!!  I can work on that using your suggestions.  Thank for your help.  I have been struggling with this problem for a long time.

**Comment by sidoh** [comment]
You're most welcome!

Milight doesn't make stuff like this easy, and some of it is impossible.

Gonna close since it sounds like this answered your question, but do let me know if I've missed something :)
