### ISSUE TITLE
Color carryover following change of bulb mode

### ISSUE THREAD

**Issue by waparo** [sidoh/esp8266_milight_hub#611]
### Color carryover following change of bulb mode.

I am using your milight hub software version 1.10.5 in an esp8266 to control ceiling down lights and have it working well.  The protocol is mqtt supplied by home assistant and python appdaemon.
There is a minor but annoying glitch somewhere in that chain, namely a very dull salmon colored nightlight is preceded by an unwanted flash of white. Here are the json commands, reported by MQTT Explorer, which cause the problem with the oldest command first.
{"status": "On", "brightness": 200, "bulb_mode": "white", "color_temp": 180}
{"status": "Off", "brightness": 0, "bulb_mode": "color"}
{"status": "On", "brightness": 2, "bulb_mode": "color", "color": {"r": 20, "g": 7, "b": 0}}

### Steps to reproduce
I would need work on that as I am currently generating a 5 second delay between the above commands just in case.

I am not really reporting a bug but hoping I will be able to fix the way I am the setting up the mqtt commands.  My searching of the net with negative results suggests that the problem may be all my own.

### Expected behavior
I expect to be able to set a light to a color x without it briefly flashing the last color y which may have been last set hours ago.

### Setup information
{"admin_username":"xx","admin_password":"yy","ce_pin":4,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"192.168.0.24:1883","mqtt_username":"xx","mqtt_password":"yy","mqtt_topic_pattern":"milight/cmnd/0x787/rgb_cct/:group_id","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"milight/state/0x787/rgb_cct/group_id","mqtt_client_status_topic":"","simple_mqtt_client_status":false,"discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":0,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"On","led_mode_operating":"Slow blip","led_mode_packet":"Flicker","led_mode_packet_count":3,"hostname":"MLHub03","rf24_power_level":"MAX","rf24_listen_channel":"HIGH","wifi_static_ip":"","wifi_static_ip_gateway":"","wifi_static_ip_netmask":"","packet_repeats_per_loop":10,"home_assistant_discovery_prefix":"homeassistant","wifi_mode":"n","default_transition_period":500,"rf24_channels":["MID","HIGH"],"device_ids":[1529,1927,7821,7822],"gateway_configs":[],"group_state_fields":["state","brightness","mode","color_temp","bulb_mode","computed_color","group_id"],"group_id_aliases":{"Hall":["rgb_cct",7822,1],"Kitchen":["rgb_cct",7822,2],"Lounge":["rgb_cct",1529,1],"Office Desk":["rgb_cct",1927,2]}}

#### Firmware version

V 1.10.5 for e12
#### Output of http://milight-hub.local/about
{"firmware":"milight-hub","version":"1.10.5","ip_address":"192.168.0.27","reset_reason":"External System","variant":"esp12","free_heap":17168,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}

"... /about output. put between the ```s"
```

#### Output of http://milight-hub.local/settings

{"admin_username":"xx","admin_password":"yy","ce_pin":4,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"192.168.0.24:1883","mqtt_username":"xx","mqtt_password":"yy","mqtt_topic_pattern":"milight/cmnd/:device_id/rgb_cct/:group_id","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"milight/state/:device_id/rgb_cct/group_id","mqtt_client_status_topic":"","simple_mqtt_client_status":false,"discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":0,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"On","led_mode_operating":"Slow blip","led_mode_packet":"Flicker","led_mode_packet_count":3,"hostname":"MLHub 02","rf24_power_level":"MAX","rf24_listen_channel":"HIGH","wifi_static_ip":"","wifi_static_ip_gateway":"","wifi_static_ip_netmask":"","packet_repeats_per_loop":10,"home_assistant_discovery_prefix":"homeassistant","wifi_mode":"n","default_transition_period":250,"rf24_channels":["MID","HIGH"],"device_ids":[],"gateway_configs":[],"group_state_fields":["state","status","brightness","mode","color_temp","bulb_mode","computed_color","group_id"],"group_id_aliases":{}}

**Comment by sidoh** [comment]
Gonna close since we discussed in #610.  :)
