### ISSUE TITLE
MQTT client unable to connect due to too small buffer (and detailed last will message)

### ISSUE THREAD

**Issue by mlewand** [sidoh/esp8266_milight_hub#613]
### Describe the bug

All of the sudden the messages received by MilightHub were not relayed to MQTT.

Turned out that MQTT broker (mosquitto) was refusing to connect the MilightHub (which was weird, because all other my esp8266 were communicating fine with MQTT).

I compiled MilightHub from the sources with debug flags, and checked mosquitto logs. Indeed the hub was attempting to connect it with proper credentials, but the client id was `<unknown>`.

Something like that was appearing in the logs:

```
1586366750: Socket error on client <unknown>, disconnecting.
```

It was surprising to me, when I realized that using a shorter [`nameBuffer`](https://github.com/sidoh/esp8266_milight_hub/blob/50e91bf63d6249348300a9c7f502f2ced949a55a/lib/MQTT/MqttClient.cpp#L58-L59) would make the hub connect, and client_id was correctly recognized by mosquitto.

Long story short, turned out that the connect message was malformed and thus mosquitto did not handle it correctly. I believe the trouble maker was this status message (it's called last will I believe?).

### Steps to reproduce

Unfortunately I have no clear repro steps 😟

### Expected behavior

Everything was working fine, except that MQTT could not connect. As a result no messages were relayed.

#### Firmware version

Latest `master` (revision 6a57ff6)

#### Output of http://milight-hub.local/about

```json
{"firmware":"milight-hub","version":"1.10.5-2-g50e91bf","ip_address":"192.168.1.40","reset_reason":"External System","variant":"esp12","free_heap":15360,"arduino_version":"2_4_2","queue_stats":{"length":0,"dropped_packets":0}}
```

#### Output of http://milight-hub.local/settings

```json
{
	"admin_username": "",
	"admin_password": "",
	"ce_pin": 4,
	"csn_pin": 15,
	"reset_pin": 0,
	"led_pin": -2,
	"radio_interface_type": "nRF24",
	"packet_repeats": 50,
	"http_repeat_factor": 1,
	"auto_restart_period": 0,
	"mqtt_server": "192.168.8.101:6832",
	"mqtt_username": "",
	"mqtt_password": "",
	"mqtt_topic_pattern": "milight/commands/:device_id/:device_type/:group_id",
	"mqtt_update_topic_pattern": "milight/updates/:hex_device_id/:device_type/:group_id",
	"mqtt_state_topic_pattern": "milight/states/:hex_device_id/:device_type/:group_id",
	"mqtt_client_status_topic": "milight/hub/client/main",
	"simple_mqtt_client_status": false,
	"discovery_port": 48899,
	"listen_repeats": 3,
	"state_flush_interval": 10000,
	"mqtt_state_rate_limit": 700,
	"packet_repeat_throttle_sensitivity": 0,
	"packet_repeat_throttle_threshold": 200,
	"packet_repeat_minimum": 3,
	"enable_automatic_mode_switching": false,
	"led_mode_wifi_config": "Fast toggle",
	"led_mode_wifi_failed": "Fast blip",
	"led_mode_operating": "Off",
	"led_mode_packet": "Flicker",
	"led_mode_packet_count": 3,
	"hostname": "milight-hub",
	"rf24_power_level": "MAX",
	"rf24_listen_channel": "LOW",
	"wifi_static_ip": "192.168.8.11",
	"wifi_static_ip_gateway": "",
	"wifi_static_ip_netmask": "",
	"packet_repeats_per_loop": 10,
	"home_assistant_discovery_prefix": "",
	"wifi_mode": "n",
	"default_transition_period": 500,
	"rf24_channels": [ "LOW", "MID", "HIGH" ],
	"device_ids": [ 4642, 8881, 13424 ],
	"gateway_configs": [],
	"group_state_fields": [],
	"group_id_aliases": {
		"Lazienka duza": [ "fut089", 13424, 1 ],
		"Maly kontroler": [ "fut089", 8881, 1 ]
	}
}
```

### Additional context

I'm sorry that I'm unable to provide a repro case - but hopefully this will be useful for people facing the same issue as I wasted couple of hours for that. I already see that [you already increased the packet size](https://github.com/sidoh/esp8266_milight_hub/blob/50e91bf63d6249348300a9c7f502f2ced949a55a/platformio.ini#L35) - but what worked for me is `360`.

Thanks for a great piece of software!

**Comment by sidoh** [comment]
Hey @mlewand, appreciate you looking into this!  Looks good.
