### ISSUE TITLE
Lights flash max brightness when going from off to x%

### ISSUE THREAD

**Issue by Tom-Jans** [sidoh/esp8266_milight_hub#623]
When i turn my lights on to x% they first flash to 100% and than go to the set percentage. They also had this issue with the milight ibox but i hoped that using esp8266_milight_hub would solve this problem.

I'm using milight MR16 4W RGB CCT lights and for controlling the lights i use openhab with node-red for automation .

**Comment by sidoh** [comment]
Bulbs always return to their previous state when they're turned on.  There's no way around this.  It's a limitation of the firmware on the bulbs.

Let me know if I've misunderstood.
