### ISSUE TITLE
Multiple Gateways Cooperate

### ISSUE THREAD

**Issue by Montie001** [sidoh/esp8266_milight_hub#628]
Would it be possible to setup the gateways to cooperate and expand range ?

I have 2 at opposite ends of the house with identical config.  Except one I dont have state / update topics set, it listens to the update topic from the other hub and sends commands.

Probably a bad setup but it usually works. I have some bulbs in range of both hubs, but wasnt sure how to setup to deal with bulbs that were in range of both

Any suggestions welcome.

**Comment by sidoh** [comment]
Hi,

Makes sense, but this is not supported.

Most commands are idempotent, so no harm in having bulbs receive the same command from two hubs. The only exception I'm aware of is up/down commands, and not all protocols have those.
