### ISSUE TITLE
WebUI "broken"

### ISSUE THREAD

**Issue by Housefrau** [sidoh/esp8266_milight_hub#634]
Hello together!

Hope you are doing all well. 

Since a few weeks (Unfortunately I cannot determine an exactly date) I am not able to get the milight-hub working properly on my nodemcuv3 CH340G. It worked like a charm for years and somewhen the WebUI just looks like in the screenshot. I tried to flash different versions, also flashed a 1MB blank file between the version switches -> No changes. :(

I flashed the firmware with the NodeMCU-Flasher for Windows (suggested in the blog) and also with PlatformIO on Unix. Both results in the "broken" WebUI.

I guess this is something I can fix myself, but honestly I just don't know how. Hopefully, someone is out there to help me out. :-)

Just let me know, if you need any further informations.

![Annotation 2020-05-27 080940](https://user-images.githubusercontent.com/59792757/82983974-7493cf00-9ff1-11ea-96f5-8c8f50850dae.png)

### What is the model number of the device you're trying to control?
FUT018

### What firmware version(s) have you tried? 
1.10.6
1.10.5
1.9.2

### Which ESP8266 board are you using? (nodemcu, d1_mini, etc.) 
nodemcuv3

### Which radio type are you using? (RGBW, RGB+CCT, etc.) 
RGBW

### Have you tried controlling the device with a physical remote?
no

#### /about

```json
{"firmware":"milight-hub","version":"1.9.2","ip_address":"192.168.201.11","reset_reason":"Software/System restart","variant":"nodemcuv2","free_heap":22328,"arduino_version":"2_4_2"}
```

#### /settings
```json
{"admin_username":"","admin_password":"","ce_pin":4,"csn_pin":15,"reset_pin":0,"led_pin":-2,"radio_interface_type":"nRF24","packet_repeats":50,"http_repeat_factor":1,"auto_restart_period":0,"mqtt_server":"","mqtt_username":"","mqtt_password":"","mqtt_topic_pattern":"","mqtt_update_topic_pattern":"","mqtt_state_topic_pattern":"","mqtt_client_status_topic":"","simple_mqtt_client_status":false,"discovery_port":48899,"listen_repeats":3,"state_flush_interval":10000,"mqtt_state_rate_limit":500,"packet_repeat_throttle_sensitivity":0,"packet_repeat_throttle_threshold":200,"packet_repeat_minimum":3,"enable_automatic_mode_switching":false,"led_mode_wifi_config":"Fast toggle","led_mode_wifi_failed":"On","led_mode_operating":"Slow blip","led_mode_packet":"Flicker","led_mode_packet_count":3,"hostname":"milight-hub","rf24_power_level":"MAX","rf24_listen_channel":"LOW","wifi_static_ip":"","wifi_static_ip_gateway":"","wifi_static_ip_netmask":"","packet_repeats_per_loop":10,"home_assistant_discovery_prefix":"","wifi_mode":"n","default_transition_period":500,"rf24_channels":["LOW","MID","HIGH"],"device_ids":[],"gateway_configs":[],"group_state_fields":["state","brightness","computed_color","mode","color_temp","bulb_mode"],"group_id_aliases":{}}
```

**Comment by Tontze** [comment]
Did you erase before flash?

**Comment by Housefrau** [comment]
> 
> 
> Did you erase before flash?

Yes I did. Could that be an hardware issue?

**Comment by Housefrau** [comment]
Never mind - I just found it. Damn.

I am using Pi-Hole in my network and it seems like the URL "maxcdn.bootstrapcdn.com" is requested, which has been blocked.

URL whitelisted -> Everything's fine.

Thanks for your time!
