### ISSUE TITLE
Switching off with remote after switching on with HA - is it possible to have proper state in HA?

### ISSUE THREAD

**Issue by akawoj** [sidoh/esp8266_milight_hub#646]
Hello!

Here is the scenario:
1. The LED are switched on with migliht_hub via Home Assistant interface
2. The LED are switch off with milight standard radio-remote
3. Status of the LEDs in HA interface is still shown as "on". **Is there any way for milight_hub** to pass info to HA, that the LED where switched off? Am I missing some configuration?

**Comment by sidoh** [comment]
Seems like this is what you're talking about?

https://github.com/sidoh/esp8266_milight_hub/wiki/Using-Milight-Remote-with-HomeAssistant

**Comment by akawoj** [comment]
Yes!

Sorry, I've missed this documentation section somehow...

**Comment by sidoh** [comment]
No worries, the docs aren't exactly perfectly organized :)
