### ISSUE TITLE
Turning on the led in color does not work - Domoticz

### ISSUE THREAD

**Issue by smarticz** [sidoh/esp8266_milight_hub#647]
### Describe the bug

In the domoticz scene editor, you must first turn on the W light, and then switch to RGB.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/68189177/87246535-51609a00-c44e-11ea-9c29-943dc48def09.png)

### Expected behavior

I would like to be able to turn on the light immediately in RGB mode

#### Firmware version
1.10.6

**Comment by sidoh** [comment]
This is not possible with Milight devices, unfortunately. Bulbs don't respond to commands when they're turned off, and return to the state they were previously in when turned on.
