### ISSUE TITLE
Unpair button - functionality not clear

### ISSUE THREAD

**Issue by kleinmantara** [sidoh/esp8266_milight_hub#651]
Hi thanks for the code.

I have several lamps that work independently of each other. Now I wanted to add a new one, I assigned a new ID and clicked on unpair - not on pair. Then the other lamps can no longer be addressed with their id. Also the new one isn't workling.

So i looked at the unpair code and I am amazed - unpair do the same like the pair code. So can you please explain how a unparing works?

```
void PacketFormatter::unpair() {
  pair();
}
```
https://github.com/sidoh/esp8266_milight_hub/blob/27a1a6ac747eacc867cea8286fc691ce7e699e55/lib/MiLight/PacketFormatter.cpp#L93

**Comment by sidoh** [comment]
What bulb type are you using?

Why isn't the functionality clear? The scenario you're describing is exactly what I'd expect to happen if you clicked the unpair button. (let me know if I'm missing something)

> So i looked at the unpair code and I am amazed - unpair do the same like the pair code. So can you please explain how a unparing works?

That's just a default implementation (PacketFormatter is a base class). Look at V2PacketFormatter.cpp, for example:

https://github.com/sidoh/esp8266_milight_hub/blob/27a1a6ac747eacc867cea8286fc691ce7e699e55/lib/MiLight/V2PacketFormatter.cpp
