### ISSUE TITLE
Handle mqtt messages without JSON

### ISSUE THREAD

**Issue by razvanws** [sidoh/esp8266_milight_hub#655]
I believe it would be great if the hub would be able to also handle the mqtt messages without the need to use JSON.

Example:
**milight/0x0/rgb_cct/1/state ON** handled the same as **milight/0x0/rgb_cct/1 {"state": "ON"}** 
**milight/0x0/rgb_cct/1/brightness 248** handled the same as **milight/0x0/rgb_cct/1 {"brightness": 248}**
In general, the same way as zigbee2mqtt does it.

The use case is the following:
I have some GU10 milight bulbs which are fitted in regular light fixtures. The light fixtures are powered by zwave Aeotec nano switches.

I would like to use home assistant default mqtt light so that I would only have one light entity which subscribes to both zwave2mqtt topics as well as milight topics. The problem is that zwave2mqtt doesn't support json and milight supports only json. Therefore, right now I'm forced to have 2 switches in home assistant which I have to keep in sync through automations which sometimes trigger unexpected results.

**Comment by sidoh** [comment]
This is unfortunately not something I see supporting -- the JSON schema is pretty baked into the project at this point. Happy to look at a PR, but I think the overhead of supporting multiple config schemas is not worth the gain.

Have you considered building a virtual switch in HomeAssistant or Node-RED that passes through messages from Zwave2MQTT in JSON format?

Going to close, but happy to continue any discussions regarding work-arounds.
