### ISSUE TITLE
UDP Command's to send? 

### ISSUE THREAD

**Issue by zierbeek** [sidoh/esp8266_milight_hub#661]
Hi! 
Is there a way to integrate the milight hub into the Tasker automation? if so, what do I need to integrate? 

I think I need to integrate the UDP sender plugin in Tasker, what are the command's to send to what port? how to configure?

**Comment by zierbeek** [comment]
Or is there a way to send a command from tasker to the milight hub

**Comment by sidoh** [comment]
If possible, I would recommend using anything other than the UDP protocol. The REST API is pretty well documented, for example --

https://sidoh.github.io/esp8266_milight_hub/branches/latest/

If you need to use the UDP protocol, please check out the [docs linked in the README](https://github.com/BKrajancic/LimitlessLED-DevAPI/).
