### ISSUE TITLE
option to add the portal via HTTPS

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#663]
Hi All,

Will it be possible to have option to access the portal via HTTPS?
I want import the portal via panel_iframe into HA.
HA is HTTPS access and then not possible to import HTTP sites into it.

Cheers,
Peter

**Comment by sidoh** [comment]
Unfortunately not without chewing through a substantial amount of already very constrained RAM. Would be possible on an ESP32, but wouldn't feel comfortable shipping HTTPS w/ ESP8266.

**Comment by poudenes** [comment]
Make sense... Most important to keep your code stable! I will close this one.
