### ISSUE TITLE
Update to gulp 4

### ISSUE THREAD

**Issue by lal12** [sidoh/esp8266_milight_hub#672]
As already mentioned in the issue #656 there is a problem building the website with nodejs >v10, since gulp 3 is incompatible. I adjusted the gulpfile to be compatible with gulp 4 and it works for me. Can I do a PR or is there any reason not to update to gulp 4?

**Comment by Zer0x00** [comment]
Just do it, the author will merge your PR or discuss it with you.

**Comment by sidoh** [comment]
Yep, sounds good to me. Working on some stray issues this morning & can look at it. Please open a PR if you're able to :)

**Comment by lal12** [comment]
Just wanted to do a PR, but apparently you were quicker. ^^
