### ISSUE TITLE
Please update wiki with homebridge integration

### ISSUE THREAD

**Issue by Zer0x00** [sidoh/esp8266_milight_hub#674]
@normen created a plugin for this project to integrate it with homebridge.

I've created the corresponding wiki files here: https://github.com/Zer0x00/esp8266_milight_hub-wiki/blob/master/Homebridge.md

Please add it to the wiki of this project.

**Comment by sidoh** [comment]
All set. Thanks for the integration, @normen & thanks for creating the docs, @Zer0x00!

**Comment by normen** [comment]
Thank you for this awesome project!
