### ISSUE TITLE
A fork variant of your code

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#678]
Saw this one, a nice idea to have behind every ESP wall switch to control bulbs.
Did you know this?

https://github.com/hencou/esp8266_milight_wallswitch

**Comment by sidoh** [comment]
Yep! Hencou has contributed a couple of things upstream as well.

**Comment by EdgardosReis** [comment]
How cool would it be if it was possible to merge that in the main repo. Define if you want to use in Hub mode or Router mode (or whatever) that create a mesh network and communicate with the hub, something like zigbee. If hencou created a fork, possible it's not easy to accomplish this without a big refactor, but it would be awesome.
