### ISSUE TITLE
MQTT group (0 "ALL")

### ISSUE THREAD

**Issue by Surtur** [sidoh/esp8266_milight_hub#680]
If someone uses only one device in group "1" and communicates via MQTT.
In the meantime, the device will be turned off from the WEB GUI by 0 "ALL", physically the device "1" will be turned off, 
but the program will not notify about the change of settings after MQTT, status "1" but only about the change in 0 "ALL".

When using the Group 0 "ALL" option.  MQTT should send the status of changes in (1; 2; 3; 4; 0)

**Comment by sidoh** [comment]
MQTT updates are intentionally not sent out in this scenario. There are nasty cases where this would cause a ton of MQTT traffic and overwhelm the hub. Would recommend not using Group 0 and instead just sending commands to the individual groups.
