### ISSUE TITLE
Question about pairing multiple lights

### ISSUE THREAD

**Issue by tinimark** [sidoh/esp8266_milight_hub#683]
Hi. I have 4 CCT panel lights on the same circuit, they are pretty inaccessible so I can only pair the four lights at the same time. Is it possible to control the panels individually if they are paired at the same time or would they need to be paired individually?

**Comment by sidoh** [comment]
They'll need to be paired separately. No way to address the panels individually when they're in pair mode -- they'll just listen for any pair command and respond to the first one they get.

**Comment by sidoh** [comment]
Gonna close since it seemed like a pretty straightforward question, but happy to continue discussing :)
