### ISSUE TITLE
Expand the Entry Limit on the Device Names

### ISSUE THREAD

**Issue by chris9012** [sidoh/esp8266_milight_hub#690]
I would like to create a device name for each one of my lights.  It appears the device list stops saving entries past 19 records.  Can this be expanded?

**Comment by sidoh** [comment]
The limitation isn't exactly 19 -- depends on what else is in your settings.

https://github.com/sidoh/esp8266_milight_hub/issues/577 is the issue for the work that needs to be done to support this. It's a pretty big change, and not one I have the time for at this moment unfortunately.

Gonna close as duplicate.
