### ISSUE TITLE
Immediate state return when using a remote ?

### ISSUE THREAD

**Issue by bcaro** [sidoh/esp8266_milight_hub#695]
Hi!
It seems that, using MQTT, when the state of a lamp is changed using a remote, a message is sent immediately.
Is it the same case with the rest API ? or using mdns ? (I think it is not the case using UDP protocol as Milight does not).
Thank's

**Comment by sidoh** [comment]
Not totally sure I understand the question, so let me know if I'm not getting it --

* When configured, state updates are sent via MQTT regardless of how the command was received. REST, UDP, and MQTT commands will all trigger an MQTT state update
* The UDP protocol is strictly 1-way. No way to get state updates with it
* The REST protocol _can_ return the state of a light when sending a command, but doesn't by default (this is done to make requests asynchronous)

**Comment by bcaro** [comment]
Ok thanks ! mqtt for 2 ways protocol

**Comment by sidoh** [comment]
👍
