### ISSUE TITLE
Get device state in Rest API : response is incomplete and differs from the documentation

### ISSUE THREAD

**Issue by bcaro** [sidoh/esp8266_milight_hub#696]
I'am able to control Milight-Hub using UDP protocol or Rest API and all seems to be fine to control the bulbs. I now try to obtain the state of the device and I have observed somme differences with the provided documentation.

Current Version
1.10.7 (nodemcuv2)
Latest Version
Version
1.10.7
Release Date
2020-11-25T02:23:40Z

- Cmd sent to hub : ""
- url : http://192.168.31.52/gateways/0x6867/rgb_cct/01 
- type : GET 

Response:
- Status:200 - 
- {"state":"ON","brightness":204,"color_temp":370,"bulb_mode":"white","color":{"r":255,"g":255,"b":255}}

I try other bulb modes and compare with the documentation here : 
https://sidoh.github.io/esp8266_milight_hub/branches/latest/
The differences are :
{
    "state": "On", -> ON/OFF
    "status": "On", -> not present
    "hue": 0, -> not present
    "saturation": 0, -> not present
    "kelvin": 0, -> not present
    "temperature": 0, -> not present
    "color_temp": 153, OK in mired
    "mode": 0, -> present if bulb_mode is scene
    "color": "255,0,255", -> object format instead : {" r ":255,"g":255,"b":255}}
    "level": 50, -> not present
    "brightness": 170, -> OK
    "effect": "night_mode", -> is  "bulb_mode" could be :[white,color,scene,night_mode]
    "transition": 2 -> not present
}

**Comment by sidoh** [comment]
The fields present in state are configurable -- select which ones you want under "Group state fields" in the MQTT tab under settings. This affects both MQTT and REST responses.
