### ISSUE TITLE
LT8900 stability regression?

### ISSUE THREAD

**Issue by Lstt2005** [sidoh/esp8266_milight_hub#70]
I try work with LT8920, it's work very stable with old branch - esp8266_milight_hub-mqtt from 20.04.2017.
But when i try work with master branch from now time - LT8920 work VERY UNSTABLE with different settings RF packets etc...((( I try REFLASH old library and master - 3 times, include SPIFFS...

**Comment by sidoh** [comment]
Can you clarify what you mean by unstable? Would also be helpful if you could share the older revision you're using that works.

**Comment by Lstt2005** [comment]
I mean, that my LED controller FUT035 work with master branch from time to time, I can not understand the patterns...with the different settings WEB UI, from web and from UDP Application..
https://cloud.mail.ru/public/4L1v/S7Z99tM6y

**Comment by sidoh** [comment]
Are you able to look at what revision you're flashing it with? From my local version of the branch it looks like 38f8fce169edb0e1f4923ccf6d7b24b30a42e910.

**Comment by sidoh** [comment]
There weren't many meaningful changes since the last commit to the mqtt branch as far as I can tell :\

https://github.com/sidoh/esp8266_milight_hub/network

**Comment by Lstt2005** [comment]
I flashing library via Platformio to my D1_mini current brach from git, and flashing https://cloud.mail.ru/public/4L1v/S7Z99tM6y from you repo from 20.04.2017.

**Comment by sidoh** [comment]
Obviously I trust that this is happening, I'm just a little confused as to why :)

Thanks for sharing the code you're flashing it with, but it'd be most helpful to get the revision. You can use `git rev-parse HEAD` to do that:

```
$ git rev-parse HEAD
38f8fce169edb0e1f4923ccf6d7b24b30a42e910
```

**Comment by sidoh** [comment]
Could you also paste the output of `/about`? Should look something like this:

```
{"version":"1.2.1-1-gf21ed22","variant":"d1_mini","free_heap":18968}
```

**Comment by Lstt2005** [comment]
Can you clarify the beginner when i do this in Windows :)) ?

**Comment by sidoh** [comment]
Ah, are you using a Windows client? There's probably a "log" option or something and you'd just look at the most recent revision.

The output of `/about` might be enough, though.

**Comment by Lstt2005** [comment]
Unfortunately, I trivially downloaded the library as a zip file, and not through the client .. (

**Comment by sidoh** [comment]
Ah, gotcha. Guessing we're on the same branch then.

Can you paste the output of `/about`? Should look like this:

![image](https://cloud.githubusercontent.com/assets/589893/25397626/b8b3afd4-299d-11e7-9afa-3687ce1b58d4.png)

**Comment by Lstt2005** [comment]
{"version":"UNKNOWN","variant":"d1_mini","free_heap":16416}

**Comment by Lstt2005** [comment]
When i flash esp8266, i see in log:
esp8266_milight_hub-master> pio run --target uploadfs
[04/25/17 21:27:30] Processing d1_mini (build_flags: !python .get_version.py -Wl,-Tesp8266.flash.4m1m.ld -D FIRMWARE_VARIANT=d1_mini; lib_
deps: SPI, , RF24, WiFiManager, ArduinoJson, PubSubClient, https://github.com/ratkins/RGBConverter; platform: espressif8266; upload_speed:
 921600; board: d1_mini; framework: arduino)
-----------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option

fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
Building SPIFFS image from 'data' directory to .pioenvs\d1_mini\spiffs.bin
/web/index.html
Looking for upload port...
Auto-detected: COM44
Uploading .pioenvs\d1_mini\spiffs.bin
Uploading 1028096 bytes from .pioenvs\d1_mini\spiffs.bin to flash at 0x00300000
................................................................................ [  7% ]
................................................................................ [ 15% ]

**Comment by sidoh** [comment]
Yeah should be fine. I'll try to replicate in the next few days.

**Comment by sidoh** [comment]
I've been playing around with the LT8900 again tonight, and it seems pretty reliable. I just switched my "production" milight hub over to an LT8900, so hopefully I'll notice any issues through daily use.

**Comment by sidoh** [comment]
LT8900 seems pretty stable in my setup. I'm going to close this, but please feel free to re-open if I'm missing something.
