### ISSUE TITLE
possible to send  command  simply by http POST  without JSON (on, off, color RGB in hexa...) µ?

### ISSUE THREAD

**Issue by tparvais** [sidoh/esp8266_milight_hub#704]
Hello

It's difficult for me  to use HTTP HTTP from my ESPEasy firmware.

is there a way to send command via  simple HTTP post ? like this
http://192.168.0.2/gateways/device_ID/Group/command

with command = ON, OFF, 0xaabbCC (RGC code) without json

thank you

**Comment by sidoh** [comment]
Hi @tparvais!

Unfortunately I don't foresee this being something I implement. I think the API supporting multiple input/output formats is not worth the complexity tradeoff given the embedded setting. If you use something like Node-RED, you could pretty easily make a translation gateway, though.
