### ISSUE TITLE
2 different state topic pattern

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#707]
Im using Milight Hub for long period. I see some tutorials and difference state topic pattern:

**MQTT state topic pattern:**
`milight/states/:device_id/:device_type/:group_id`
and
`milight/states/:hex_device_id/:device_type/:group_id`

Can someone tell me what is the difference? Or what is better?

**Comment by poudenes** [comment]
nobody? ;)

**Comment by ccutrer** [comment]
Those are the same. :hex_device_id is a synonym to make it clear which version you want. there is also :dec_device_id if you want decimal. :device_id is always hex though, just not as clear in the name
