### ISSUE TITLE
Wrong naming for color temparature

### ISSUE THREAD

**Issue by golddragon007** [sidoh/esp8266_milight_hub#713]
### Describe the bug
Color temp is measured in Kelvins. The MQTT message contains the following:
  "kelvin": 100,
  "color_temp": 370,
Where the kelvin key's value is not Kelvin, it's the percentage of the color temp bar. While the color_temp is actually kelvin values divided by 10.

### Expected behavior
"kelvin" needs to be renamed to something else.

#### Output of http://milight-hub.local/about

```json
"... /about output. put between the ```s"
```

#### Output of http://milight-hub.local/settings

```json
"... /settings output. put between the ```s"
```

**Comment by sidoh** [comment]
I know this is inaccurate and misleading, but there are too many integrations built on top of the API at this point to change the key.

color_temp is the white temperature measured in Mireds (it's not kelvin).

See API docs:

https://sidoh.github.io/esp8266_milight_hub/branches/latest/#tag/Device-Control/paths/~1gateways~1{device-id}~1{remote-type}~1{group-id}/put
