### ISSUE TITLE
HA 2021.3.0 change MQTT Light  template schema

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#717]
Hi All,

Maybe interesting and maybe a need to change things:

The MQTT light with template schema will now send a `float` instead of an `int` with the transition key.

https://github.com/home-assistant/core/pull/46385

for now everything seems to work normal... but I don't know if things will removed in later versions.

Cheers,
Peter

**Comment by sidoh** [comment]
Pretty sure float values are already supported -- do you notice any issues?

**Comment by poudenes** [comment]
Everything seems to work fine... It was just a post so you know the change of HA

**Comment by sidoh** [comment]
appreciate the heads up!
