### ISSUE TITLE
Is it possible implement new OEM (partially Milight) protocol?

### ISSUE THREAD

**Issue by itProfi** [sidoh/esp8266_milight_hub#72]
I recieve yesterday some RGBW OEM China LED plate - https://detail.1688.com/offer/522143371857.html?spm=a2615.2177701.0.0.hO79R9
When i sniff it, i see this syncword 0x050A 0x55AA and channels 0x04 (4) and 0x4A( 74), command with 7 byte payload, like 0xC2 0xDC 0xA0 0xAB 0x01 0xBE 0x00 (Power On All), 0xC2 0xDC 0xA0 0xAB 0x02 0xC1 0x00 (power Off ALL).
I believe that this is very similar to the description of the old MiLigh protocol - http://arduino-projects4u.com/milight-rf-control/
Can you help me for it's implemention?

**Comment by sidoh** [comment]
Sure, if you can figure out the command structure I can take a look.

**Comment by Lstt2005** [comment]
Ok, thanks. But only after the 2 of May..)

**Comment by tbrasser** [comment]
it's probably one of the controllers on this page: http://www.futlight.com/productlist.aspx?typeid=146&page=1

**Comment by itProfi** [comment]
Hi, Chris!
Yesterday, i again try investigate those packets with some modificatios on MilightRadioConfig.cpp

**Comment by sidoh** [comment]
Compile with DEBUG_PRINTF on.  Listening with LT8900 is pretty broken honestly.  Would recommend using the nRF24.

**Comment by itProfi** [comment]
I sniff all button from my remote via nRF24:
![OEM_partially_milight](https://user-images.githubusercontent.com/6728198/60769848-540f0d80-a0dd-11e9-82e4-61417464c53b.jpg)
[oem_milight.txt](https://github.com/sidoh/esp8266_milight_hub/files/3365735/oem_milight.txt)
Please, help!!

**Comment by itProfi** [comment]
Chris, help, please..)

**Comment by sidoh** [comment]
This is pretty different.  Honestly don't think it makes sense to add support unless there is for some reason a lot of people with this same device.  Can offer some tips on decoding it and adding support in your own fork, though.

**Comment by itProfi** [comment]
OK .. If you can, give advice on his support in my fork..

**Comment by itProfi** [comment]
Chris?

**Comment by sidoh** [comment]
sorry, not going to have time to give detailed instructions.  you can check out this PR adding support for a new remote type:

https://github.com/sidoh/esp8266_milight_hub/pull/490

you'll need to decode the packet structure yourself, though.

**Comment by itProfi** [comment]
ok, thanks..i try..))

**Comment by sidoh** [comment]
Nice.  It looked pretty similar to RGBW structure, for what it's worth.  Gonna close the issue, but happy to continue the discussion.  Good luck!

**Comment by ZeMilkmann** [comment]
@itProfi Did you ever finish implementing this protocol? I have a RGB+CCT lamp with a remote I couldn't sniff with the default configuration but the lamp pairs and reacts to an old CCT remote I had laying around. 
Trying to sniff that gives me  what I have written below, so I assume we may have the same or a very similar protocol

```
cct packet received (7 bytes):
Request type  : 5A
```
