### ISSUE TITLE
Default value for "packet_repeats" and "http_repeat_factor"

### ISSUE THREAD

**Issue by WoodsterDK** [sidoh/esp8266_milight_hub#75]
Might want to add some default values for these, as a complete fresh install cannot send, but only receive frames.

**Comment by sidoh** [comment]
A complete fresh install with flash wiped should default to 10 and 5, respectively:

```
    packetRepeats(10),
    httpRepeatFactor(5),
```

Has this not been your experience?

**Comment by WoodsterDK** [comment]
Strange, the fields were empty in the web app.

**Comment by sidoh** [comment]
This is after clearing flash on another ESP:

![image](https://cloud.githubusercontent.com/assets/589893/25672807/0d433e64-2fea-11e7-97c6-3f8c37454388.png)

It's possible older versions didn't play nicely with even older settings blobs, but I think the newest version should do what it's supposed to.

Are you able to replicate?

**Comment by WoodsterDK** [comment]
Let's close it up... might be a bad flash routine.

**Comment by sidoh** [comment]
Cool. Thanks anyway for raising. :)
