### ISSUE TITLE
Support of API connection with HA

### ISSUE THREAD

**Issue by poudenes** [sidoh/esp8266_milight_hub#782]
Hi ALl,

I moved my ESPeasy wall switches to ESPhome and it's brilliant !!! Many things added also a neopixel and it's connected directly to Home Assistant using the native API implementation.

Would be great to have this also in the Milight image.

https://esphome.io/components/api.html?highlight=api

If this can implement then usage of MQTT is not needed anymore. And its much faster

**Comment by scottmckenzie** [comment]
You can add a UDP gateway and use the LimitlessLED integration:
https://www.home-assistant.io/integrations/limitlessled/
