### ISSUE TITLE
MQTT setup example

### ISSUE THREAD

**Issue by axelrathey** [sidoh/esp8266_milight_hub#789]
Hi,

Can you give a setup example to use it with mosquitto MQTT broker.
Are there wildcards in the mqtt pattern allowed?
What is the difference between "MQTT update topic pattern" and "MQTT status topic pattern" and "MQTT Client Status Topic"?

I tried different things but there ist nothing else as $SYS to bee seen on mosquitto MQTT broker. Other MQTT clients like instar camera works on my mosquitto.

I tried something like "milight/0x155C/#" for the pattern

Thanks Axel

**Comment by Linkenelis** [comment]
> Hi Linkenelis, tanks a lot, now it works. The cmnd ist to switch the lamps from within mqtt? Axel
Yes
