### ISSUE TITLE
2 hubs

### ISSUE THREAD

**Issue by Bollemp3** [sidoh/esp8266_milight_hub#790]
Hi,

I had made two hubs, I setup both hubs with a different IP and host names… but if I control 1 the second is responding the same?!?

what I can do about this so I got 2 different hubs?

Sorry I have a lot of Mi-Light ceiling lamps ☺️

**Comment by Linkenelis** [comment]
You control 1, how? Web-page, MQTT, API, UDP

If both respond to web-page, API or UDP using different ip, that would be odd. MQTT could be same topic problem.

**Comment by Bollemp3** [comment]
I found what I did wrong . Sorry… I didn’t address the device ID… so on both of the hubs the first 8 channels of the FUT089 where addressed the same 😅
My bad ✌🏼

**Comment by Linkenelis** [comment]
np
