### ISSUE TITLE
Not all devices are showing on MQTT auto discovery - some prefixed with "none_" 

### ISSUE THREAD

**Issue by southwalesboy** [sidoh/esp8266_milight_hub#808]
In version 1.11.0 the Home Assistant has picked up some duplicates of the saved light aliases with the prefix "none_".

One of my lights keep disappearing from Home Assistant, it is there occasionally, but not consistently. The others seem to work correctly.

**Comment by sidoh** [comment]
Oh man, sorry for the late reply here.

If you're still having this issue, can you paste the output of `/aliases`?

**Comment by sidoh** [comment]
Gonna close but please feel free to re-open if you're still having trouble
