### ISSUE TITLE
Would this work with FUT038S

### ISSUE THREAD

**Issue by nmcc1212** [sidoh/esp8266_milight_hub#811]
I have these RGBW LED strip controllers
![image](https://github.com/sidoh/esp8266_milight_hub/assets/48334675/2de3ecf7-b224-49d4-bfb5-e5f807cd4ae8)

Would this work with these

**Comment by garmck** [comment]
@nmcc1212 I have the FUT035 of this version and it works fine for me

**Comment by sidoh** [comment]
Sounds like question is answered so gonna close. Thanks @garmck
