### ISSUE TITLE
More than 4 groups?

### ISSUE THREAD

**Issue by otto2704** [sidoh/esp8266_milight_hub#813]
Hi,

probably I am just too stupid. But how to setup more than 4 groups? The webui only shows group 1-4 and all.
How to add groups?
Best regards and thanks in advance,
Otto

**Comment by sidoh** [comment]
Hey Otto,

You can accomplish this by using different device IDs. You can use any device ID from 0 to 65535 and any one of 4 groups with each of the device IDs.
