### ISSUE TITLE
changing brightness while off

### ISSUE THREAD

**Issue by KitKat-ok** [sidoh/esp8266_milight_hub#821]
Hello how could I set the brightness while the state is Off so that I can set the brightness to zero before turning the state On so the brighntess is immediatialy 0. I cant find a way to do it I tried to do it with transitions but it first flashes the brightness that was set before and then changes it to 0

**Comment by sidoh** [comment]
Unfortunately this is impossible with Milight bulbs. The only commands they respond to while off is the one to turn them on.

There is a "night mode" that some bulbs have -- basically dimmer than even 0% brightness while 'on'. I don't remember for sure, but it might be possible to turn on night mode while they're off. I don't think you can set the brightness even in night mode, though.
