### ISSUE TITLE
Home Assistant mqtt_json

### ISSUE THREAD

**Issue by WoodsterDK** [sidoh/esp8266_milight_hub#84]
Hi there,

a question - is white_value expected to be supported ?

**Comment by sidoh** [comment]
No, just color_temp atm. They seemed redundant. Easy enough to add, though:

https://github.com/sidoh/esp8266_milight_hub/blob/master/lib/MiLight/MiLightClient.cpp#L291

**Comment by WoodsterDK** [comment]
Ok, I just noticed the option. The color temp slider works just fine turning the white on.
