### ISSUE TITLE
ESP32 no WIFI shows up

### ISSUE THREAD

**Issue by CyberHummel** [sidoh/esp8266_milight_hub#856]
Hello, i am using an ESP 32 Development Board,
i can flash the firmware, however if it finishes, after i restart it it doesnt show up in my WIFI Network and i cant seem to find it.

**Comment by daverof** [comment]
I have the same issue, whether I flash at `0x0` or `0x1000`. If you check the serial log (easy way is with ESPHome web flasher), it'll either hang or be stuck in a boot loop with various messages. This means it's not starting up fully, which is why the Wi-Fi isn't showing.

**Comment by sidoh** [comment]
@CyberHummel, it won't connect automatically to your wifi network. There's a wifi setup process that you'll need to go through first (see [this section](https://github.com/sidoh/esp8266_milight_hub?tab=readme-ov-file#configure-wifi) in the README).

@daverof, you definitely need to flash the firmware image at `0x1000` for ESP32. If you're seeing issues and this is your first time flashing the project on your ESP32, you probably need to set up the partition table (I'm using a non-default flash layout to fit the web assets in flash). The easiest way to do that is with platformio: `platformio run -e esp32 --target upload`.

README should be updated to reflect this. I meant to do that but got distracted.

**Comment by daverof** [comment]
Thank you! It worked after a full erase with `esptool` and the flash itself by `platformio` rather than `esptool`.

**Comment by CyberHummel** [comment]
How did you flash it with PlatformIO?

**Comment by CyberHummel** [comment]
Nevermind, got it to work with PlatformIO!
After installing Python XD (Forgot i have a new PC)
