### ISSUE TITLE
Can you use this firmware with an actual milight hub

### ISSUE THREAD

**Issue by sam150122** [sidoh/esp8266_milight_hub#857]
Can this firmware be used with the original milight hub?
I have one of the small round ones with a colour changing led in and some GU10 milight bulbs that I would like to use but the home assistant integration isn't great with the stock firmware.
Can I flash this onto the hub?

**Comment by Zer0x00** [comment]
No, the original hub can't be flashed. You need an ESP8266 or ESP32.

**Comment by sidoh** [comment]
@Zer0x00 is correct, this is specifically for ESP8266/ESP32.
