### ISSUE TITLE
Zones

### ISSUE THREAD

**Issue by RvonMallesch** [sidoh/esp8266_milight_hub#90]
Hi there,

If this controller allows you to control 262,144 zones, would you kindly explain why the web interface allows you to select from just 4?

Regards,

Richard

**Comment by rhamblen** [comment]
Simple
You can set lots and lots of groups of 4 by changing the id.
I have 5 groups off the controller.

From Richard
Sent from my iPhone
---------------------------------
Don't forget my email is still richardh@iname.com I just use google as my outbound mail at the moment for technical reasons.
----------------------------------

**Comment by RvonMallesch** [comment]
OK, thanks!

**Comment by sidoh** [comment]
Thanks, Richard!
